/* Dre After Dark · Life OS — Ritual initiation + completion timing */
(()=>{'use strict';const K='dreLifeOS',$=s=>document.querySelector(s),uid=()=>crypto.randomUUID?.()||Date.now()+'-'+Math.random(),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function read(){try{let d=JSON.parse(localStorage.getItem(K)||'{}');d.activitySessions=d.activitySessions||[];return d}catch{return{activitySessions:[]}}}function save(d){localStorage.setItem(K,JSON.stringify(d));window.dispatchEvent(new CustomEvent('lifeos:data-changed',{detail:{source:'activity-timing'}}))}
function today(x){return new Date(x).toDateString()===new Date().toDateString()}function active(id){return read().activitySessions.find(x=>x.activityId===id&&!x.finishedAt)}
function start(id,name){let d=read();if(d.activitySessions.some(x=>x.activityId===id&&!x.finishedAt))return;let now=new Date().toISOString();d.activitySessions.push({id:uid(),activityId:id,name,plannedAt:now,startedAt:now,finishedAt:null,startFriction:'',finishNote:''});d.events=d.events||[];d.events.push({id:uid(),at:now,domain:'habit',type:'activity-start',detail:name,sourceId:id});save(d);render()}
function finish(id){let d=read(),x=d.activitySessions.find(x=>x.activityId===id&&!x.finishedAt);if(!x)return;let now=new Date().toISOString();x.finishedAt=now;d.events=d.events||[];d.events.push({id:uid(),at:now,domain:'habit',type:'activity-finish',detail:x.name,sourceId:id,durationMinutes:Math.max(0,Math.round((new Date(now)-new Date(x.startedAt))/60000))});save(d);if(window.completeHabit){try{window.completeHabit(id)}catch(e){}}ask(x.id);setTimeout(function(){window.HabitCommand?.render?.();render()},140)}
function ask(sessionId){let m=$('#modal'),c=$('#modalContent');if(!m||!c)return;c.innerHTML='<p class="eyebrow">INITIATION INTELLIGENCE</p><h2>What affected getting started?</h2><p class="quiet">Optional. This helps Life OS learn the difference between planning something and actually initiating it.</p><select id="friction"><option value="">Skip / no strong factor</option><option>Easy to start</option><option>Forgot / lost track of time</option><option>Low energy</option><option>Task felt too big</option><option>Unclear first step</option><option>Distracted / hyperfocused elsewhere</option><option>Environment / interruption</option><option>Emotional resistance</option><option>Waiting on something</option></select><textarea id="finishNote" placeholder="Anything else worth remembering?"></textarea><button id="saveFriction" class="primary">Save reflection</button>';m.classList.remove('hidden');$('#saveFriction').onclick=()=>{let d=read(),x=d.activitySessions.find(y=>y.id===sessionId);if(x){x.startFriction=$('#friction').value;x.finishNote=$('#finishNote').value.trim();save(d)}m.classList.add('hidden')}}
function stats(){let a=read().activitySessions.filter(x=>x.startedAt),done=a.filter(x=>x.finishedAt),dur=done.map(x=>(new Date(x.finishedAt)-new Date(x.startedAt))/60000).filter(Number.isFinite);return{started:a.length,finished:done.length,avg:dur.length?Math.round(dur.reduce((n,x)=>n+x,0)/dur.length):0}}
function render(){let root=$('#habitCommand');if(!root)return;root.querySelectorAll('[data-complete]').forEach(b=>{let id=b.dataset.complete,row=b.closest('.habit-priority'),name=row?.querySelector('b')?.textContent||id;if(!row)return;let x=active(id),btn=row.querySelector('[data-activity-start]');if(!btn){btn=document.createElement('button');btn.type='button';btn.className='ghost activity-timer';btn.dataset.activityStart=id;row.appendChild(btn)}btn.textContent=x?'Finish':'Start';btn.onclick=()=>active(id)?finish(id):start(id,name);let stamp=row.querySelector('[data-activity-stamp]');if(!stamp){stamp=document.createElement('small');stamp.dataset.activityStamp=id;stamp.className='activity-stamp';row.appendChild(stamp)}if(x){let dt=new Date(x.startedAt);stamp.textContent='Started '+dt.toLocaleDateString()+' · '+dt.toLocaleTimeString([],{hour:'numeric',minute:'2-digit'});row.classList.add('activity-running')}else{let d=read(),last=d.activitySessions.filter(y=>y.activityId===id&&y.finishedAt).at(-1);stamp.textContent=last?'Last finished '+new Date(last.finishedAt).toLocaleDateString()+' · '+new Date(last.finishedAt).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'}):'';row.classList.remove('activity-running')}});let s=stats(),box=$('#initiationSignal');if(!box){box=document.createElement('div');box.id='initiationSignal';box.className='ii-item';root.querySelector('.habit-command')?.appendChild(box)}if(box)box.innerHTML='<b>Initiation signal</b><br><small>'+s.started+' started · '+s.finished+' finished · '+s.avg+' min average recorded duration</small>'}
document.addEventListener('click',e=>{if(e.target.closest?.('nav button[data-view="habits"]'))setTimeout(render,120);if(e.target.closest?.('[data-complete]'))setTimeout(render,180)},true);window.addEventListener('lifeos:data-changed',()=>setTimeout(render,80));window.ActivityTiming={start,finish,stats,render};})();
