/* Archive QA v2 — explicit range filtering, time-aware axes, summaries, correction */
(()=>{'use strict';const KEY='dreLifeOS',el=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const db=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return {events:[]}}};
const day=86400000;
function rangeInfo(v){let n=+v||30;return {days:n,label:n===365?'1 year':`${n} days`}}
function startFor(days){let d=new Date();d.setHours(23,59,59,999);d.setDate(d.getDate()-days+1);d.setHours(0,0,0,0);return d}
function bucketSpec(days){if(days<=7)return {kind:'day',step:1};if(days<=30)return {kind:'day',step:5};if(days<=90)return {kind:'month'};return {kind:'month'}}
function buckets(days){let now=new Date(),start=startFor(days),spec=bucketSpec(days),out=[];if(spec.kind==='month'){let d=new Date(start.getFullYear(),start.getMonth(),1);while(d<=now){let next=new Date(d.getFullYear(),d.getMonth()+1,1);out.push({a:new Date(Math.max(d,start)),b:new Date(Math.min(+next-1,+now)),label:d.toLocaleDateString(undefined,{month:'short',year:days>=365?'2-digit':undefined})});d=next}}else{for(let d=new Date(start);d<=now;){let a=new Date(d),b=new Date(d);b.setDate(b.getDate()+spec.step-1);if(b>now)b=new Date(now);out.push({a,b,label:spec.step===1?a.toLocaleDateString(undefined,{month:'short',day:'numeric'}):`${a.toLocaleDateString(undefined,{month:'short',day:'numeric'})}–${b.toLocaleDateString(undefined,{month:'short',day:'numeric'})}`});d.setDate(d.getDate()+spec.step)}}return out}
function filtered(days){let cut=startFor(days);return (db().events||[]).filter(e=>new Date(e.at)>=cut)}
function series(ev,domain,bs){return bs.map(b=>ev.filter(e=>(!domain||e.domain===domain)&&new Date(e.at)>=b.a&&new Date(e.at)<=b.b).length)}
function chart(id,values,labels){let c=el(id);if(!c)return;let ratio=devicePixelRatio||1,w=Math.max(300,c.clientWidth),h=245;c.width=w*ratio;c.height=h*ratio;c.style.height=h+'px';let x=c.getContext('2d');x.scale(ratio,ratio);x.clearRect(0,0,w,h);let left=32,right=10,top=16,bottom=46,pw=w-left-right,ph=h-top-bottom,max=Math.max(1,...values);x.strokeStyle='rgba(198,165,106,.22)';x.fillStyle='#bbaeb4';x.font='11px system-ui';for(let i=0;i<3;i++){let y=top+ph*i/2;x.beginPath();x.moveTo(left,y);x.lineTo(w-right,y);x.stroke();let val=Math.round(max*(1-i/2));x.fillText(String(val),4,y+4)}let bw=pw/Math.max(1,values.length);x.fillStyle='#c6a56a';values.forEach((v,i)=>{let bh=v/max*ph;x.fillRect(left+i*bw+bw*.18,top+ph-bh,Math.max(3,bw*.64),bh)});x.fillStyle='#bbaeb4';x.textAlign='center';let every=Math.max(1,Math.ceil(labels.length/6));labels.forEach((lab,i)=>{if(i%every&&i!==labels.length-1)return;x.fillText(lab,left+i*bw+bw/2,h-24)});x.textAlign='left'}
function ensureUI(){let range=el('range');if(!range)return;let head=range.closest('.sectionhead');if(head&&!el('archiveRangeProof')){let p=document.createElement('div');p.id='archiveRangeProof';p.className='card';p.style.margin='0 0 1rem';p.innerHTML='<p class="eyebrow">ACTIVE ANALYSIS WINDOW</p><h3 id="archiveWindowTitle"></h3><p id="archiveWindowDates" class="quiet"></p><p id="archiveWindowCount"></p>';head.insertAdjacentElement('afterend',p)}let table=el('eventTable')?.closest('table');let hr=table?.querySelector('thead tr');if(hr&&!hr.querySelector('[data-correction-head]')){let th=document.createElement('th');th.dataset.correctionHead='1';th.textContent='Correction';hr.appendChild(th)}}
function render(){ensureUI();let range=el('range');if(!range)return;let {days,label}=rangeInfo(range.value),ev=filtered(days),bs=buckets(days),start=startFor(days),now=new Date();el('archiveWindowTitle').textContent=`Showing ${label}`;el('archiveWindowDates').textContent=`${start.toLocaleDateString()} → ${now.toLocaleDateString()} · ${bucketSpec(days).kind==='month'?'monthly':'day-based'} graph buckets`;el('archiveWindowCount').textContent=`${ev.length} recorded events in this window`;let domains={habit:'Habit events',house:'House events',plant:'Plant care'};let money=(db().events||[]).filter(e=>e.domain==='money'&&new Date(e.at)>=start).reduce((a,e)=>a+(+e.amount||0),0);let metrics=el('metrics');if(metrics)metrics.innerHTML=[...Object.entries(domains).map(([d,n])=>[n,ev.filter(e=>e.domain===d).length]),['Services avoided','$'+money.toFixed(0)]].map(x=>`<div class="metric"><span>${x[0]}</span><b>${x[1]}</b></div>`).join('');chart('habitChart',series(ev,'habit',bs),bs.map(b=>b.label));chart('houseChart',series(ev,'house',bs),bs.map(b=>b.label));chart('plantChart',series(ev,'plant',bs),bs.map(b=>b.label));let energyBs=bs,energyVals=energyBs.map(b=>ev.filter(e=>new Date(e.at)>=b.a&&new Date(e.at)<=b.b).length);chart('energyChart',energyVals,energyBs.map(b=>b.label));let body=el('eventTable');if(body)body.innerHTML=ev.slice().reverse().slice(0,100).map(e=>`<tr><td>${new Date(e.at).toLocaleDateString()}</td><td>${esc(e.domain)}</td><td>${esc(e.type)}</td><td>${esc(e.detail||e.energy||'')}</td><td><button class="ghost archive-correct-v2" data-id="${esc(e.id)}">Correct</button></td></tr>`).join('')}
function correct(id){let d=db(),i=(d.events||[]).findIndex(e=>e.id===id);if(i<0)return;if(!confirm('Remove this event from your Life OS history?'))return;d.events.splice(i,1);localStorage.setItem(KEY,JSON.stringify(d));render();document.dispatchEvent(new CustomEvent('lifeos:archive-corrected',{detail:{id}}))}
function boot(){ensureUI();el('range')?.addEventListener('change',()=>setTimeout(render,0));document.addEventListener('click',e=>{let b=e.target.closest('.archive-correct-v2');if(b)correct(b.dataset.id);let nav=e.target.closest('button[data-view="archive"]');if(nav)setTimeout(render,20)});window.addEventListener('storage',render);setTimeout(render,100)}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',boot,{once:true}):boot();window.LifeArchiveQA={render};})();