/* Archive QA v5 — local-day buckets, clean mobile axes, summaries, exactly one correction column */
(()=>{'use strict';const KEY='dreLifeOS',el=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const db=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return {events:[]}}};
function rangeInfo(v){let n=+v||30;return {days:n,label:n===365?'1 year':`${n} days`}}
function dayStart(d=new Date()){let x=new Date(d);x.setHours(0,0,0,0);return x}function dayEnd(d=new Date()){let x=new Date(d);x.setHours(23,59,59,999);return x}function startFor(days){let d=dayStart();d.setDate(d.getDate()-days+1);return d}
function bucketSpec(days){if(days<=7)return {kind:'day',step:1};if(days<=30)return {kind:'day',step:5};return {kind:'month'}}const short=d=>d.toLocaleDateString(undefined,{month:'short',day:'numeric'});
function buckets(days){let now=new Date(),start=startFor(days),spec=bucketSpec(days),out=[];if(spec.kind==='month'){let d=new Date(start.getFullYear(),start.getMonth(),1);while(d<=now){let next=new Date(d.getFullYear(),d.getMonth()+1,1),a=new Date(Math.max(+d,+start)),b=new Date(Math.min(+next-1,+now));out.push({a:dayStart(a),b:dayEnd(b),label:d.toLocaleDateString(undefined,{month:'short',year:days>=365?'2-digit':undefined})});d=next}}else{for(let d=new Date(start);d<=now;){let a=dayStart(d),b=new Date(a);b.setDate(b.getDate()+spec.step-1);b=dayEnd(b>now?now:b);out.push({a,b,label:short(a)});d=new Date(a);d.setDate(d.getDate()+spec.step)}}return out}
function eventDate(e){let d=new Date(e.at);return Number.isNaN(+d)?null:d}function filtered(days){let cut=startFor(days),end=dayEnd();return (db().events||[]).filter(e=>{let d=eventDate(e);return d&&d>=cut&&d<=end})}function series(ev,domain,bs){return bs.map(b=>ev.reduce((n,e)=>{let d=eventDate(e);return n+(d&&(!domain||e.domain===domain)&&d>=b.a&&d<=b.b?1:0)},0))}
function chart(id,values,labels){let c=el(id);if(!c)return;let ratio=devicePixelRatio||1,w=Math.max(300,c.clientWidth),h=245;c.width=w*ratio;c.height=h*ratio;c.style.height=h+'px';let x=c.getContext('2d');x.scale(ratio,ratio);x.clearRect(0,0,w,h);let left=34,right=12,top=16,bottom=42,pw=w-left-right,ph=h-top-bottom,max=Math.max(1,...values);x.strokeStyle='rgba(198,165,106,.22)';x.fillStyle='#bbaeb4';x.font='10px system-ui';for(let i=0;i<3;i++){let y=top+ph*i/2;x.beginPath();x.moveTo(left,y);x.lineTo(w-right,y);x.stroke();x.fillText(String(Math.round(max*(1-i/2))),4,y+4)}let bw=pw/Math.max(1,values.length);x.fillStyle='#c6a56a';values.forEach((v,i)=>{if(v<=0)return;let bh=Math.max(2,v/max*ph);x.fillRect(left+i*bw+bw*.2,top+ph-bh,Math.max(3,bw*.6),bh)});x.fillStyle='#bbaeb4';x.textAlign='center';let slots=w<520?4:6,every=Math.max(1,Math.ceil(labels.length/slots));labels.forEach((lab,i)=>{if(i%every&&i!==labels.length-1)return;x.fillText(lab,left+i*bw+bw/2,h-20)});x.textAlign='left'}
function ensureUI(){let range=el('range');if(!range)return;let head=range.closest('.sectionhead');if(head&&!el('archiveRangeProof')){let p=document.createElement('div');p.id='archiveRangeProof';p.className='card';p.style.margin='0 0 1rem';p.innerHTML='<p class="eyebrow">ACTIVE ANALYSIS WINDOW</p><h3 id="archiveWindowTitle"></h3><p id="archiveWindowDates" class="quiet"></p><p id="archiveWindowCount"></p>';head.insertAdjacentElement('afterend',p)}let hr=el('eventTable')?.closest('table')?.querySelector('thead tr');if(hr)hr.innerHTML='<th>Date</th><th>Domain</th><th>Event</th><th>Detail</th><th>Correction</th>'}
function render(){ensureUI();let range=el('range');if(!range)return;let {days,label}=rangeInfo(range.value),ev=filtered(days),bs=buckets(days),start=startFor(days),now=new Date();el('archiveWindowTitle').textContent=`Showing ${label}`;el('archiveWindowDates').textContent=`${start.toLocaleDateString()} → ${now.toLocaleDateString()} · ${bucketSpec(days).kind==='month'?'monthly':'day-based'} graph buckets`;el('archiveWindowCount').textContent=`${ev.length} recorded events in this window`;let domains={habit:'Habit events',house:'House events',plant:'Plant care'},money=ev.filter(e=>e.domain==='money').reduce((a,e)=>a+(+e.amount||0),0),metrics=el('metrics');if(metrics)metrics.innerHTML=[...Object.entries(domains).map(([d,n])=>[n,ev.filter(e=>e.domain===d).length]),['Services avoided','$'+money.toFixed(0)]].map(x=>`<div class="metric"><span>${x[0]}</span><b>${x[1]}</b></div>`).join('');chart('habitChart',series(ev,'habit',bs),bs.map(b=>b.label));chart('houseChart',series(ev,'house',bs),bs.map(b=>b.label));chart('plantChart',series(ev,'plant',bs),bs.map(b=>b.label));chart('energyChart',series(ev,null,bs),bs.map(b=>b.label));let body=el('eventTable');if(body)body.innerHTML=ev.slice().sort((a,b)=>+eventDate(b)-+eventDate(a)).slice(0,100).map(e=>`<tr><td>${eventDate(e).toLocaleDateString()}</td><td>${esc(e.domain)}</td><td>${esc(e.type)}</td><td>${esc(e.detail||e.energy||'')}</td><td><button class="ghost archive-correct-v2" data-id="${esc(e.id)}">Correct</button></td></tr>`).join('')}
function correct(id){let d=db(),i=(d.events||[]).findIndex(e=>e.id===id);if(i<0)return;if(!confirm('Remove this event from your Life OS history?'))return;d.events.splice(i,1);localStorage.setItem(KEY,JSON.stringify(d));render();document.dispatchEvent(new CustomEvent('lifeos:archive-corrected',{detail:{id}}))}
function enforce(){let body=el('eventTable');if(!body)return;[...body.rows].forEach(r=>{while(r.cells.length>5)r.deleteCell(r.cells.length-1)});ensureUI()}
function boot(){ensureUI();el('range')?.addEventListener('change',()=>setTimeout(render,0));document.addEventListener('click',e=>{let b=e.target.closest('.archive-correct-v2');if(b)correct(b.dataset.id);let nav=e.target.closest('button[data-view="archive"]');if(nav)setTimeout(render,20)});let body=el('eventTable');if(body)new MutationObserver(()=>requestAnimationFrame(enforce)).observe(body,{childList:true,subtree:true});window.addEventListener('storage',render);setTimeout(render,100)}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',boot,{once:true}):boot();window.LifeArchiveQA={render};})();