/* Dre After Dark · Life OS — Google sign-in via Supabase Auth */
(()=>{
const SB='https://alwtccdiyudsucfioahr.supabase.co',KEY='sb_publishable_v1AZYAfBP6vA0nrxcWQI6g_sWFt5PYU',APP='https://fempai.github.io/dre-after-dark-life-os/';
let client;
async function boot(){if(!window.supabase){const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2';await new Promise((r,j)=>{s.onload=r;s.onerror=j;document.head.appendChild(s)})}client=window.supabase.createClient(SB,KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});upgrade();await paint();client.auth.onAuthStateChange(()=>setTimeout(paint,0));}
async function signIn(){const {error}=await client.auth.signInWithOAuth({provider:'google',options:{redirectTo:APP,scopes:'openid email profile'}});if(error)paintError(error.message)}
async function signOut(){await client.auth.signOut();await paint()}
function paintError(t){const x=document.getElementById('cloudState');if(x)x.textContent='Sign-in needs attention: '+t}
async function paint(){const {data:{session}}=await client.auth.getSession();const x=document.getElementById('cloudState'),g=document.getElementById('googleLifeSignIn'),o=document.getElementById('googleLifeSignOut');if(session){if(x)x.textContent=`Cloud identity connected · ${session.user.email||'Google account'}`;if(g)g.classList.add('hidden');if(o)o.classList.remove('hidden')}else{if(x)x.textContent='Sign in with Google to protect cloud data and persistent integrations.';if(g)g.classList.remove('hidden');if(o)o.classList.add('hidden')}}
function upgrade(){const cloud=document.getElementById('cloudState')?.closest('article');if(!cloud||document.getElementById('googleLifeSignIn'))return;const old=['email','password','signup','signin','signout'];old.forEach(id=>{const e=document.getElementById(id);if(e)e.style.display='none'});const wrap=document.createElement('div');wrap.innerHTML=`<button id="googleLifeSignIn" class="primary" style="width:100%;margin:.75rem 0">G&nbsp;&nbsp; Continue with Google</button><button id="googleLifeSignOut" class="ghost hidden" style="width:100%;margin:.5rem 0">Sign out of Life OS</button><p class="quiet">Your Google password is never entered into or stored by Life OS.</p>`;cloud.insertBefore(wrap,document.getElementById('syncBtn'));document.getElementById('googleLifeSignIn').onclick=signIn;document.getElementById('googleLifeSignOut').onclick=signOut;}
window.LifeAuth={signIn,signOut,getClient:()=>client};document.readyState==='loading'?document.addEventListener('DOMContentLoaded',boot):boot();
})();