/* Life OS — release backup/restore guard */
(()=>{'use strict';const K='dreLifeOS',$=s=>document.querySelector(s);
function read(){try{return JSON.parse(localStorage.getItem(K)||'{}')}catch{return{}}}
function status(t){let s=$('#backupStatus');if(s)s.textContent=t}
function validate(x){if(!x||typeof x!=='object'||Array.isArray(x))throw Error('Backup is not a Life OS object.');let known=['events','habits','plants','brain','quotes','personalLabs','domainLabs','journal','health','relationship','calendar'];if(!known.some(k=>k in x))throw Error('This file does not contain recognizable Life OS data.');return x}
function exportBackup(){let d=read(),payload={...d,_lifeOSBackup:{format:1,exportedAt:new Date().toISOString(),app:'Dre After Dark · Life OS'}};let blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='dre-life-os-backup-'+new Date().toISOString().slice(0,10)+'.json';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);status('Backup exported · '+new Date().toLocaleTimeString([],{hour:'numeric',minute:'2-digit'}))}
function importBackup(input){let f=input.files?.[0];if(!f)return;status('Validating backup…');let r=new FileReader();r.onload=()=>{try{let next=validate(JSON.parse(r.result));delete next._lifeOSBackup;if(!confirm('Restore this verified Life OS backup? Your current local structured data will be replaced.')){status('Restore cancelled. Current data unchanged.');return}localStorage.setItem(K,JSON.stringify(next));status('Backup restored successfully. Reloading Life OS…');setTimeout(()=>location.reload(),350)}catch(e){status('Backup rejected · '+e.message)}finally{input.value=''}};r.onerror=()=>{status('Backup could not be read. Current data unchanged.');input.value=''};r.readAsText(f)}
function bind(){let e=$('#exportBtn'),i=$('#importInput');if(e)e.onclick=ev=>{ev.preventDefault();exportBackup()};if(i)i.onchange=()=>importBackup(i)}
function boot(){bind();setTimeout(bind,600);setTimeout(bind,1600)}document.readyState==='loading'?document.addEventListener('DOMContentLoaded',boot,{once:true}):boot();window.LifeBackup={exportBackup,validate};
})();