/* Dre After Dark · Life OS — Calendar through the single Supabase identity */
(()=>{
const SB='https://alwtccdiyudsucfioahr.supabase.co', KEY='sb_publishable_v1AZYAfBP6vA0nrxcWQI6g_sWFt5PYU';
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[m]));
function state(){try{return JSON.parse(localStorage.getItem('dreLifeOS')||'{}')}catch{return {}}} function save(s){localStorage.setItem('dreLifeOS',JSON.stringify(s))}
function log(type,detail,extra={}){let s=state();s.events=s.events||[];s.events.push({id:crypto.randomUUID(),at:new Date().toISOString(),domain:'calendar',type,detail,...extra});save(s)}
function status(t){if($('#googleCalendarState'))$('#googleCalendarState').textContent=t}
async function session(){if(!window.LifeAuth)throw Error('Life OS identity is still loading.');return await window.LifeAuth.getSession()}
async function call(action,extra={}){let s=await session();if(!s)throw Error('Sign in with Google to Life OS first.');let r=await fetch(`${SB}/functions/v1/google-calendar`,{method:'POST',headers:{Authorization:`Bearer ${s.access_token}`,'Content-Type':'application/json',apikey:KEY},body:JSON.stringify({action,...extra})});let j=await r.json();if(!r.ok)throw Error(j.error||'Calendar service error');return j}
async function connect(){try{status('Preparing secure Google Calendar authorization…');let j=await call('authorize');location.href=j.url}catch(e){status(e.message)}}
async function check(){try{let s=await session();if(!s){status('Sign in to Life OS first, then connect Calendar.');return}let j=await call('status');if(j.connected){status(`Persistently connected${j.email?' · '+j.email:''}`);await sync()}else status('Life OS identity connected · Calendar not connected yet.')}catch(e){status(e.message)}}
async function sync(){try{status('Syncing through secure backend…');let j=await call('sync'),items=(j.events||[]).map(e=>({id:e.google_event_id,title:e.summary,start:e.starts_at,end:e.ends_at,htmlLink:e.html_link,status:e.status,allDay:e.all_day}));if((j.synced??items.length)!==items.length)throw Error(`Calendar verification mismatch: backend reported ${j.synced}, returned ${items.length}.`);let s=state(),stamp=new Date().toISOString();s.calendar={...(s.calendar||{}),lastSync:stamp,verifiedCount:items.length,events:items};save(s);let verify=state().calendar;if(!verify||verify.events?.length!==items.length||verify.verifiedCount!==items.length)throw Error('Calendar local persistence verification failed.');render(items);detect(items);status(`Calendar verified · ${items.length} upcoming events · ${new Date().toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}`)}catch(e){status('Calendar sync needs attention. '+e.message)}}
async function disconnect(){try{await call('disconnect');let s=state();s.calendar={events:[]};save(s);render([]);status('Google Calendar disconnected.')}catch(e){status(e.message)}}
async function createEvent(){let title=prompt('Calendar event title');if(!title)return;let st=prompt('Start (YYYY-MM-DDTHH:MM)',new Date(Date.now()+3600000).toISOString().slice(0,16));if(!st)return;let en=prompt('End (YYYY-MM-DDTHH:MM)',new Date(new Date(st).getTime()+3600000).toISOString().slice(0,16));if(!en)return;try{await call('create',{event:{summary:title,start:{dateTime:new Date(st).toISOString()},end:{dateTime:new Date(en).toISOString()}}});log('event-created',title);await sync()}catch(e){status('Could not add event. '+e.message)}}
function render(items){let b=$('#calendarAgenda');if(!b)return;b.innerHTML=!items.length?'<p class="quiet">No upcoming Calendar events loaded.</p>':items.slice(0,12).map(e=>{let d=new Date(e.start);return `<div class="task"><div><b>${esc(e.title)}</b><br><span class="quiet">${d.toLocaleDateString([],{weekday:'short',month:'short',day:'numeric'})}${e.allDay?' · all day':' · '+d.toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}</span></div></div>`}).join('')}
function detect(items){let today=new Date().toDateString(),conf=items.filter(e=>new Date(e.start).toDateString()===today&&!e.allDay).filter(e=>{let h=new Date(e.start).getHours();return h>=17&&h<22}),b=$('#calendarConflicts');if(!b)return;b.innerHTML=!conf.length?'':`<article class="card accent"><p class="eyebrow">SCHEDULE COLLISION</p><h3>${conf.length===1?esc(conf[0].title):conf.length+' evening events'} may overlap the home rhythm.</h3><p>This is context, not failure.</p><div class="row"><button onclick="LifeCalendar.adjustTonight()">Adjust tonight</button><button onclick="LifeCalendar.keepRoutine()">Keep routine</button><button onclick="LifeCalendar.decideLater()">Decide later</button></div></article>`}
function choice(type,label){log('conflict-'+type,label);if($('#calendarConflicts'))$('#calendarConflicts').innerHTML=`<article class="card"><p class="eyebrow">CALENDAR CONTEXT RECORDED</p><p>${esc(label)}</p></article>`}
function ui(){let settings=$('#settingsConnections .sg-body')||$('#settings .grid.two')||$('#settings');if(settings&&!$('#googleCalendarCard')){let a=document.createElement('article');a.className='card';a.id='googleCalendarCard';a.innerHTML=`<p class="eyebrow">CALENDAR CONTEXT ENGINE</p><h2>Google Calendar</h2><p id="googleCalendarState">Checking Life OS identity…</p><div class="row"><button id="gcalConnect" class="primary">Connect Google Calendar</button><button id="gcalSync">Sync now</button><button id="gcalDisconnect" class="ghost">Disconnect</button></div><button id="gcalAdd">+ Add event to Google Calendar</button><h3>Next 30 days</h3><div id="calendarAgenda"></div><p class="quiet">Calendar uses your Life OS Supabase session. The private backend stores the Google refresh token; secrets never enter GitHub or browser storage.</p>`;settings.appendChild(a);$('#gcalConnect').onclick=connect;$('#gcalSync').onclick=sync;$('#gcalDisconnect').onclick=disconnect;$('#gcalAdd').onclick=createEvent}let today=$('#today');if(today&&!$('#calendarConflicts')){let x=document.createElement('div');x.id='calendarConflicts';today.insertBefore(x,today.children[1]||null)}render(state().calendar?.events||[]);let q=new URLSearchParams(location.search);if(q.get('calendar')){history.replaceState({},'',location.pathname);status(q.get('calendar')==='connected'?'Google authorization received. Finishing connection…':'Google authorization needs attention.')}setTimeout(check,250)}
window.LifeCalendar={connect,sync,disconnect,createEvent,adjustTonight:()=>choice('adjust','Tonight was intentionally adjusted around calendar context.'),keepRoutine:()=>choice('keep','Routine retained despite the calendar collision.'),decideLater:()=>choice('later','Decision deferred; no missed-ritual judgment recorded.')};
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',ui):ui();
})();