/* Dre After Dark · Life OS — Google Calendar integration */
(() => {
const CLIENT_ID='1026019682076-gr8apsuo41v75oa4le0mmvrer7uojeae.apps.googleusercontent.com';
const SCOPES='https://www.googleapis.com/auth/calendar.readonly https://www.googleapis.com/auth/calendar.events';
let tokenClient=null, token=null;
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function state(){try{return JSON.parse(localStorage.getItem('dreLifeOS')||'{}')}catch{return {}}}
function save(s){localStorage.setItem('dreLifeOS',JSON.stringify(s))}
function log(type,detail,extra={}){let s=state();s.events=s.events||[];s.events.push({id:crypto.randomUUID(),at:new Date().toISOString(),domain:'calendar',type,detail,...extra});save(s)}
function status(t){let e=$('#googleCalendarState');if(e)e.textContent=t}
function loadGIS(){return new Promise((res,rej)=>{if(window.google?.accounts?.oauth2)return res();let x=document.createElement('script');x.src='https://accounts.google.com/gsi/client';x.async=true;x.defer=true;x.onload=res;x.onerror=rej;document.head.appendChild(x)})}
async function init(){await loadGIS();tokenClient=google.accounts.oauth2.initTokenClient({client_id:CLIENT_ID,scope:SCOPES,include_granted_scopes:true,callback:async r=>{if(r.error){status('Authorization failed: '+r.error);return}token=r;sessionStorage.setItem('lifeosGoogleToken',JSON.stringify(r));status('Google Calendar connected.');log('authorized','Calendar access granted',{scope:r.scope});await sync();}});let cached=sessionStorage.getItem('lifeosGoogleToken');if(cached){try{token=JSON.parse(cached);status('Google Calendar connected for this session.');sync()}catch{}}}
function connect(){if(!tokenClient)return status('Google authorization is still loading…');tokenClient.requestAccessToken({prompt:token?'':'consent'})}
function disconnect(){if(token?.access_token&&window.google)google.accounts.oauth2.revoke(token.access_token,()=>{});token=null;sessionStorage.removeItem('lifeosGoogleToken');status('Google Calendar disconnected.');render([])}
async function api(path,opts={}){if(!token?.access_token)throw Error('Connect Google Calendar first.');let r=await fetch('https://www.googleapis.com/calendar/v3'+path,{...opts,headers:{Authorization:'Bearer '+token.access_token,'Content-Type':'application/json',...(opts.headers||{})}});if(r.status===401){token=null;sessionStorage.removeItem('lifeosGoogleToken');status('Calendar authorization expired. Tap Connect to renew.');throw Error('Authorization expired')}if(!r.ok)throw Error(await r.text());return r.status===204?{}:r.json()}
async function sync(){try{status('Syncing calendar…');let now=new Date(),end=new Date(now);end.setDate(end.getDate()+14);let q=`/calendars/primary/events?singleEvents=true&orderBy=startTime&timeMin=${encodeURIComponent(now.toISOString())}&timeMax=${encodeURIComponent(end.toISOString())}&maxResults=100`;let data=await api(q),items=(data.items||[]).map(e=>({id:e.id,title:e.summary||'(Untitled)',start:e.start?.dateTime||e.start?.date,end:e.end?.dateTime||e.end?.date,htmlLink:e.htmlLink,status:e.status,updated:e.updated}));let s=state();s.calendar=s.calendar||{};s.calendar.lastSync=new Date().toISOString();s.calendar.events=items;save(s);log('sync',`${items.length} upcoming events synchronized`,{count:items.length});render(items);detect(items);status(`Connected · ${items.length} upcoming events · synced ${new Date().toLocaleTimeString([], {hour:'numeric',minute:'2-digit'})}`)}catch(e){status('Calendar sync needs attention. '+e.message)}}
function render(items){let box=$('#calendarAgenda');if(!box)return;if(!items.length){box.innerHTML='<p class="quiet">No upcoming Calendar events loaded.</p>';return}box.innerHTML=items.slice(0,12).map(e=>{let d=new Date(e.start),allDay=!String(e.start).includes('T');return `<div class="task"><div><b>${esc(e.title)}</b><br><span class="quiet">${d.toLocaleDateString([], {weekday:'short',month:'short',day:'numeric'})}${allDay?' · all day':' · '+d.toLocaleTimeString([], {hour:'numeric',minute:'2-digit'})}</span></div></div>`}).join('')}
function detect(items){let today=new Date().toDateString(),conf=items.filter(e=>new Date(e.start).toDateString()===today&&String(e.start).includes('T')).filter(e=>{let h=new Date(e.start).getHours();return h>=17&&h<22});let box=$('#calendarConflicts');if(!box)return;if(!conf.length){box.innerHTML='';return}box.innerHTML=`<article class="card accent"><p class="eyebrow">SCHEDULE COLLISION</p><h3>${conf.length===1?esc(conf[0].title):conf.length+' evening events'} may overlap the home rhythm.</h3><p>This is context, not failure. Life OS will preserve the deviation as data.</p><div class="row"><button onclick="LifeCalendar.adjustTonight()">Adjust tonight</button><button onclick="LifeCalendar.keepRoutine()">Keep routine</button><button onclick="LifeCalendar.decideLater()">Decide later</button></div></article>`}
function choice(type,label){log('conflict-'+type,label);let b=$('#calendarConflicts');if(b)b.innerHTML=`<article class="card"><p class="eyebrow">CALENDAR CONTEXT RECORDED</p><p>${esc(label)}</p></article>`}
async function createEvent(){let title=prompt('Calendar event title');if(!title)return;let start=prompt('Start (YYYY-MM-DDTHH:MM)',new Date(Date.now()+3600000).toISOString().slice(0,16));if(!start)return;let end=prompt('End (YYYY-MM-DDTHH:MM)',new Date(new Date(start).getTime()+3600000).toISOString().slice(0,16));if(!end)return;try{await api('/calendars/primary/events',{method:'POST',body:JSON.stringify({summary:title,start:{dateTime:new Date(start).toISOString()},end:{dateTime:new Date(end).toISOString()}})});log('event-created',title);await sync()}catch(e){status('Could not add event. '+e.message)}}
function installUI(){let settings=$('#settings .grid.two');if(settings&&!$('#googleCalendarCard')){let a=document.createElement('article');a.className='card';a.id='googleCalendarCard';a.innerHTML=`<p class="eyebrow">CALENDAR CONTEXT ENGINE</p><h2>Google Calendar</h2><p id="googleCalendarState">Not connected.</p><div class="row"><button id="gcalConnect" class="primary">Connect Google Calendar</button><button id="gcalSync">Sync now</button><button id="gcalDisconnect" class="ghost">Disconnect</button></div><button id="gcalAdd">+ Add event to Google Calendar</button><h3>Next 14 days</h3><div id="calendarAgenda"></div><p class="quiet">Life OS reads calendar context, detects collisions, and can create events only when you explicitly ask. Calendar changes become longitudinal context.</p>`;settings.appendChild(a);$('#gcalConnect').onclick=connect;$('#gcalSync').onclick=sync;$('#gcalDisconnect').onclick=disconnect;$('#gcalAdd').onclick=createEvent}
let today=$('#today');if(today&&!$('#calendarConflicts')){let x=document.createElement('div');x.id='calendarConflicts';today.insertBefore(x,today.children[1]||null)}let s=state();render(s.calendar?.events||[])}
window.LifeCalendar={connect,sync,disconnect,adjustTonight:()=>choice('adjust','Tonight was intentionally adjusted around calendar context.'),keepRoutine:()=>choice('keep','Routine retained despite the calendar collision.'),decideLater:()=>choice('later','Decision deferred; no missed-ritual judgment recorded.'),createEvent};
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',()=>{installUI();init()}):(installUI(),init());
})();