/* Dre After Dark · Life OS — Unified Chronicle + temporal intelligence */
(()=>{'use strict';const K='dreLifeOS',$=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));function read(){try{return JSON.parse(localStorage.getItem(K)||'{}')}catch{return{}}}function entries(days=30){let d=read(),since=Date.now()-days*86400000,a=[],seen=new Set(),add=x=>{let t=new Date(x.at).getTime(),key=x.id||x.sourceId||[x.at,x.domain,x.type,x.text].join('|');if(Number.isFinite(t)&&t>=since&&!seen.has(key)){seen.add(key);a.push(x)}};
(d.signals||[]).forEach(x=>add({id:x.id,at:x.at,domain:x.domain||'life',type:x.type||'signal',text:x.label||x.detail||x.type,source:x.source||'signals',sourceId:x.sourceId||x.id}));
(d.events||[]).forEach(x=>add({id:x.id,at:x.at,domain:x.domain||'life',type:x.type||'event',text:x.detail||x.label||x.type,source:x.source||'events',sourceId:x.id}));
(d.plants||[]).forEach(p=>{(p.events||[]).forEach(x=>add({id:x.id,at:x.at,domain:'plant',type:x.type||'plant-event',text:[p.nickname,x.detail||x.label||x.type].filter(Boolean).join(' · '),source:'conservatory',sourceId:x.id}));(p.notes||[]).forEach(x=>add({id:x.id,at:x.at,domain:'plant',type:'specimen-note',text:[p.nickname,x.text].filter(Boolean).join(' · '),source:'conservatory',sourceId:x.id}))});
(d.commandCenter?.chronicle||[]).forEach(x=>add({id:x.id,at:x.at,domain:'journal',type:'milestone',text:x.text,source:'command-center',sourceId:x.id}));
(d.commandCenter?.cabinet||[]).forEach(x=>add({id:x.id,at:x.at,domain:'archive',type:'cabinet',text:x.text,source:'command-center',sourceId:x.id}));
(d.personalLabs?.logs||[]).forEach(x=>add({id:x.id,at:x.at||x.createdAt,domain:x.lab||x.domain||'personal',type:x.type||'personal-log',text:x.note||x.text||x.title||x.type||'Personal Lab log',source:'personal-labs',sourceId:x.id}));
(d.personalLabs?.scans||[]).forEach(x=>add({id:x.id,at:x.at,domain:x.dest||'scan',type:'scan',text:x.note||x.name||'Saved scan',source:'personal-labs',sourceId:x.id}));
(d.brain||[]).forEach((x,i)=>add({id:x.id||'brain-'+i+'-'+x.at,at:x.at,domain:'capture',type:'brain-dump',text:x.text||'Captured thought',source:'today',sourceId:x.id}));
(d.personalLabs?.records||[]).forEach(x=>add({id:x.id,at:x.at,domain:x.lab||'personal',type:'structured-record',text:Object.values(x.fields||{}).filter(Boolean).join(' · ')||x.type||'Personal Lab record',source:'personal-labs',sourceId:x.id}));
Object.entries(d.domainLabs||{}).forEach(([lab,rows])=>(rows||[]).forEach(x=>add({id:x.id,at:x.at,domain:lab,type:x.type||'domain-record',text:[x.name,x.status,x.note,x.amount,x.targetDate].filter(v=>v!==null&&v!==''&&v!==undefined).join(' · ')||x.type||lab,source:'domain-labs',sourceId:x.id})));
(d.calendar?.events||[]).forEach(x=>add({id:x.id,at:x.start,domain:'calendar',type:'calendar-event',text:x.title||'Calendar event',source:'calendar',sourceId:x.id}));
(window.DiscoveryEngine?.history?.()||[]).forEach(x=>add({id:x.id,at:x.at,domain:'chronicle',type:x.type||'milestone',text:x.title||x.text,source:'discovery',sourceId:x.id}));return a.sort((x,y)=>new Date(y.at)-new Date(x.at))}function temporal(days=30){let a=entries(days),hours=Array(24).fill(0),week=Array(7).fill(0),domains={};a.forEach(x=>{let d=new Date(x.at);hours[d.getHours()]++;week[d.getDay()]++;domains[x.domain]=(domains[x.domain]||0)+1});let peak=hours.indexOf(Math.max(...hours)),active=Object.entries(domains).sort((a,b)=>b[1]-a[1]).slice(0,4);return{days,total:a.length,peakHour:a.length?peak:null,activeDomains:active,weekdayCounts:week}}function render(){let h=$('#chronicleEngine');if(!h)return,t=temporal(30),a=entries(30);h.innerHTML=`<article class="card"><p class="eyebrow">THE CHRONICLE</p><h2>Life Timeline + Temporal Intelligence</h2><p>${t.total} recorded moments in the last 30 days${t.peakHour!=null?` · activity most often recorded around ${new Date(2000,0,1,t.peakHour).toLocaleTimeString([],{hour:'numeric'})}`:''}.</p>${t.activeDomains.length?`<p class="quiet">Most represented domains: ${t.activeDomains.map(([k,v])=>`${esc(k)} (${v})`).join(' · ')}</p>`:''}<div style="max-height:420px;overflow:auto">${a.slice(0,60).map(x=>`<div class="ii-item"><small>${new Date(x.at).toLocaleString()} · <b>${esc(x.domain)}</b> · ${esc(x.type)}</small><div>${esc(x.text)}</div></div>`).join('')||'<p class="quiet">The Chronicle will fill as Life OS records your activity.</p>'}</div></article>`}function install(){return true}function boot(){let n=0,t=setInterval(()=>{if(install()||++n>30)clearInterval(t)},200)}document.readyState==='loading'?document.addEventListener('DOMContentLoaded',boot,{once:true}):boot();window.LifeChronicle={entries,temporal};})();