/* Dre After Dark · Life OS — External Publishing Metrics Bridge */
(()=>{const KEY='dreLifeOS_externalMetrics',II='dreLifeOS_ii',SB='https://alwtccdiyudsucfioahr.supabase.co';
const load=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{"wordpress":{"site":"drebattles.wordpress.com"},"instagram":{}}')}catch{return{wordpress:{site:'drebattles.wordpress.com'},instagram:{}}}},save=d=>localStorage.setItem(KEY,JSON.stringify(d)),ii=()=>{try{return JSON.parse(localStorage.getItem(II)||'{"books":[],"content":[],"metrics":[]}')}catch{return{books:[],content:[],metrics:[]}}},saveII=d=>{localStorage.setItem(II,JSON.stringify(d));window.LifeSignals?.reconcile?.();window.dispatchEvent(new CustomEvent('lifeos:externalmetrics'))},norm=s=>String(s||'').toLowerCase().replace(/<[^>]*>/g,'').replace(/&[^;]+;/g,' ').replace(/[^a-z0-9]+/g,' ').trim(),match=(title,list)=>{let t=norm(title);return list.find(x=>norm(x.title)===t)||list.find(x=>t&&norm(x.title).includes(t))||list.find(x=>norm(x.title)&&t.includes(norm(x.title)))};
async function callWP(action,extra={}){const session=await window.LifeAuth?.getSession?.();if(!session)throw Error('Sign in with Google first.');let r=await fetch(`${SB}/functions/v1/wordpress`,{method:'POST',headers:{Authorization:`Bearer ${session.access_token}`,'Content-Type':'application/json'},body:JSON.stringify({action,...extra})});let j=await r.json().catch(()=>({}));if(!r.ok)throw Error(j.error||`WordPress ${r.status}`);return j}
async function wordpressStatus(){return callWP('status')}
async function connectWordPress(){let j=await callWP('authorize');if(!j.url)throw Error('WordPress authorization URL was not returned.');location.href=j.url}
async function disconnectWordPress(){return callWP('disconnect')}
function mergePosts(posts){let d=ii(),added=0,linked=0;(posts||[]).forEach(p=>{let c=d.content.find(x=>String(x.externalId)===String(p.post_id))||match(p.title,d.content);if(c){c.platform='WordPress';c.externalId=p.post_id;c.externalUrl=p.url;c.publishedAt=c.publishedAt||p.published_at;c.status='Published';linked++}else{d.content.push({id:`wp-${p.post_id}`,title:p.title,type:'Blog',status:'Published',platform:'WordPress',externalId:p.post_id,externalUrl:p.url,publishedAt:p.published_at,createdAt:p.published_at,noteIds:[]});added++}});saveII(d);return{added,linked}}
async function syncWordPress(){let j=await callWP('sync'),m=mergePosts(j.posts||[]);let session=await window.LifeAuth.getSession(),client=await window.LifeAuth.getClient();let {data:rows}=await client.from('wordpress_metrics_cache').select('post_id,captured_at,views,visitors,likes,comments,reblogs,email_opens,email_clicks').eq('user_id',session.user.id).order('captured_at',{ascending:false}).limit(500);ingestWordPressStats((rows||[]).map(r=>({postId:r.post_id,at:r.captured_at,...r})));return{...j,...m}}
function ingestWordPressStats(rows){let d=ii(),count=0;rows.forEach(r=>{let c=d.content.find(x=>String(x.externalId)===String(r.postId))||match(r.title,d.content);if(!c)return;let id=`wpmetric-${c.id}-${r.at||Date.now()}`;if(d.metrics.some(x=>x.id===id))return;d.metrics.push({id,at:r.at||new Date().toISOString(),contentId:c.id,name:c.title,platform:'WordPress',source:'api',views:+r.views||0,likes:+r.likes||0,comments:+r.comments||0,saves:0,shares:+r.reblogs||0,visitors:+r.visitors||0,emailOpens:+r.email_opens||0,emailClicks:+r.email_clicks||0});count++});saveII(d);return count}
function ingestInstagramMedia(media){let d=ii(),count=0;media.forEach(r=>{let title=r.title||r.caption?.split('\n')[0]?.slice(0,100)||`Instagram ${r.media_type||'post'}`,c=d.content.find(x=>String(x.externalId)===String(r.id))||match(title,d.content);if(!c){c={id:`ig-${r.id}`,title,type:r.media_type==='VIDEO'?'Reel':'Instagram Post',status:'Published',platform:'Instagram',externalId:String(r.id),externalUrl:r.permalink||'',publishedAt:r.timestamp||new Date().toISOString(),createdAt:r.timestamp||new Date().toISOString(),noteIds:[]};d.content.push(c)}else{c.platform='Instagram';c.externalId=String(r.id);c.externalUrl=r.permalink||c.externalUrl;c.publishedAt=c.publishedAt||r.timestamp;c.status='Published'}d.metrics.push({id:`igmetric-${r.id}-${r.at||Date.now()}`,at:r.at||new Date().toISOString(),contentId:c.id,name:c.title,platform:'Instagram',source:'api',views:+(r.views??r.reach??r.impressions)||0,reach:+r.reach||0,likes:+r.likes||0,comments:+r.comments||0,saves:+r.saved||0,shares:+r.shares||0});count++});saveII(d);return count}
function config(){return load()}function setConfig(patch){let d=load();Object.keys(patch).forEach(k=>d[k]={...(d[k]||{}),...patch[k]});save(d);return d}window.ExternalMetrics={config,setConfig,wordpressStatus,connectWordPress,disconnectWordPress,syncWordPress,syncWordPressPosts:syncWordPress,ingestWordPressStats,ingestInstagramMedia};})();