/* Dre After Dark · Life OS — Insight Engine · stabilized */
(()=>{const mean=a=>a.length?a.reduce((n,x)=>n+x,0)/a.length:null,round=n=>n==null?null:+n.toFixed(2),today=()=>new Date().toISOString().slice(0,10);
function model(){let signals=window.LifeSignals?.query?.()||[],patterns=window.PatternEngine?.model?.()||{},profiles=window.PatternEngine?.profiles?.()||[],cal=window.LifeSignals?.calendarProfile?.()||{},insights=[];
const add=x=>insights.push({id:x.id||`ins-${insights.length}`,status:x.status||'question',class:x.class||'behavior',title:x.title,text:x.text,evidence:x.evidence||{},confidence:x.confidence||'insufficient',recommendation:x.recommendation||null,why:x.why||null});
(patterns.hypotheses||[]).forEach((h,i)=>add({id:`pattern-${i}`,status:h.evidence==='descriptive association only'?'emerging':'question',class:h.context||'body-environment',title:'Longitudinal pattern',text:h.text,confidence:h.evidence==='descriptive association only'?'emerging':'insufficient',evidence:{type:h.evidence||'data readiness'},why:'Derived from repeated day-level comparisons in the Pattern Engine.'}));
(cal.hypotheses||[]).forEach((h,i)=>add({id:`calendar-${i}`,status:h.status==='candidate'?'emerging':'question',class:'schedule',title:'Schedule pattern',text:h.text,confidence:h.status==='candidate'?'emerging':'insufficient',evidence:{scheduledDays:cal.comparisons?.sample?.scheduledDays||0,openDays:cal.comparisons?.sample?.openDays||0,type:h.evidence||'data readiness'},why:'Derived from scheduled-day versus open-day observations.'}));
let recent=profiles.slice(-14),todayProfile=profiles.find(x=>x.date===today()),habitBase=mean(recent.map(x=>+x.habitSignals||0)),readingBase=mean(recent.map(x=>+x.readingSignals||0));
let readiness={status:'learning',score:null,reasons:[],sample:recent.length};if(todayProfile){let score=50;if(todayProfile.calendarEvents){score-=Math.min(20,(todayProfile.calendarEvents||0)*5);readiness.reasons.push(`${todayProfile.calendarEvents} scheduled event${todayProfile.calendarEvents===1?'':'s'} today`)}if(todayProfile.bodySignals){score-=10;readiness.reasons.push('body/health context logged today')}if(todayProfile.environmentSignals){score+=5;readiness.reasons.push('environmental maintenance activity logged')}readiness.score=Math.max(0,Math.min(100,score));readiness.status=recent.length<7?'learning':score>=65?'favorable':score>=40?'mixed':'strained'}
let predictions=[];if(recent.length>=7&&todayProfile){predictions.push({outcome:'habit activity',baseline:round(habitBase),direction:todayProfile.calendarEvents?'potentially below baseline':'near personal baseline',confidence:recent.length>=21?'developing':'emerging',sample:recent.length,reason:todayProfile.calendarEvents?'Today contains scheduled demands; historical schedule comparisons should be consulted.':'No scheduled demand is currently represented in today’s profile.'});predictions.push({outcome:'reading activity',baseline:round(readingBase),direction:todayProfile.calendarEvents?'watch schedule interference':'no schedule penalty inferred',confidence:recent.length>=21?'developing':'emerging',sample:recent.length,reason:'Prediction is a readiness cue, not a guarantee.'})}
let recommendations=[];if(readiness.status==='strained'||readiness.status==='mixed')recommendations.push({title:'Protect initiation, not perfection',text:'Use the smallest viable version of established rituals and preserve recovery capacity around today’s demands.',basis:'Current-day schedule/body context plus your longitudinal model.',confidence:recent.length>=7?'emerging':'low'});if(todayProfile?.calendarEvents)recommendations.push({title:'Use the calendar as scaffolding',text:'Anchor one important routine before or after a fixed event instead of relying on an ideal uninterrupted day.',basis:'Today contains scheduled structure.',confidence:'contextual'});if(!recommendations.length)recommendations.push({title:'Keep the ordinary day observable',text:'Follow the normal plan and log deviations. Ordinary days are necessary comparison data for stronger future recommendations.',basis:'Evidence-building requirement.',confidence:'high'});
return{generatedAt:new Date().toISOString(),signals:signals.length,insights,readiness,predictions,recommendations,guardrail:'Predictions are historical estimates, not certainties. Recommendations are suggestions based on observed context and remain revisable as evidence changes.'}}
window.InsightEngine={model};try{window.dispatchEvent(new CustomEvent('lifeos:insights',{detail:model()}))}catch(e){console.warn('[InsightEngine] startup model failed',e)}
})();