/* Dre After Dark · Life OS — Unified Signal / Integration Layer
   One common language across habits, calendar, care, home, conservatory and I&I.
   Raw module data remains authoritative; signals are normalized, rebuildable indexes.
*/
(()=>{
const OS_KEY='dreLifeOS',II_KEY='dreLifeOS_ii',SCHEMA=1;
const read=(k,f={})=>{try{return JSON.parse(localStorage.getItem(k)||'null')||f}catch{return f}};
const write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const uid=()=>crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random()}`;
const iso=v=>{try{return new Date(v||Date.now()).toISOString()}catch{return new Date().toISOString()}};
const day=v=>iso(v).slice(0,10);
const text=v=>String(v??'').trim();
const slug=v=>text(v).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,80)||'item';
const hash=s=>{let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return (h>>>0).toString(36)};
const stable=(source,parts)=>`sig-${source}-${hash(parts.map(text).join('|'))}`;
function state(){let s=read(OS_KEY,{events:[]});s.events=s.events||[];s.signals=s.signals||[];s.signalLinks=s.signalLinks||[];s.integration=s.integration||{};return s}
function save(s){write(OS_KEY,s)}
function normalize(x={}){return {id:x.id||uid(),schema:SCHEMA,at:iso(x.at),day:day(x.at),domain:text(x.domain)||'life',type:text(x.type)||'observation',label:text(x.label||x.detail||x.type),value:x.value??null,unit:text(x.unit)||null,source:text(x.source)||'life-os',sourceId:text(x.sourceId)||null,energy:text(x.energy)||null,context:x.context&&typeof x.context==='object'?x.context:{},tags:[...new Set((x.tags||[]).map(slug).filter(Boolean))],links:[...new Set((x.links||[]).filter(Boolean))],privacy:x.privacy||'private',evidence:x.evidence||'observation',meta:x.meta&&typeof x.meta==='object'?x.meta:{}}}
function upsert(s,x){x=normalize(x);let i=s.signals.findIndex(v=>v.id===x.id);if(i<0)s.signals.push(x);else s.signals[i]={...s.signals[i],...x};return x}
function eventSignal(e){let sid=e.id||stable('event',[e.at,e.domain,e.type,e.detail]);return {id:`sig-event-${sid}`,at:e.at,domain:e.domain||'life',type:e.type||'event',label:e.detail||e.type,source:'life-events',sourceId:sid,energy:e.energy||null,value:e.amount??e.count??null,context:{calendarRelated:e.domain==='calendar',householdRelated:['house','plant'].includes(e.domain),behavioral:true},tags:[e.domain,e.type],meta:{rawEventId:e.id||null}}}
function calendarSignals(s){return (s.calendar?.events||[]).map(e=>({id:stable('calendar',[e.id,e.start]),at:e.start,domain:'calendar',type:'scheduled-event',label:e.title,source:'google-calendar',sourceId:e.id,context:{end:e.end||null,allDay:!!e.allDay,status:e.status||null,scheduled:true},tags:['calendar','schedule',e.allDay?'all-day':'timed'],links:e.htmlLink?[e.htmlLink]:[]}))}
function careSignals(s){let out=[];(s.health||[]).forEach(x=>out.push({id:`sig-health-${x.id||hash(JSON.stringify(x))}`,at:x.at,domain:'health',type:x.kind||'observation',label:x.note,source:'care-dossier',sourceId:x.id,context:{area:x.area,hypothesis:x.hypothesis||null,clinicianQuestion:x.question||null},tags:['health',x.area,x.kind],links:x.link?[x.link]:[],evidence:'observation'}));(s.relationship||[]).forEach(x=>out.push({id:`sig-relationship-${x.id||hash(JSON.stringify(x))}`,at:x.at,domain:'relationship',type:'reflection',label:x.event,source:'relationship-self-study',sourceId:x.id,context:{relationshipContext:x.context,interpretation:x.interpretation,response:x.response,need:x.need,nextExperiment:x.next},tags:['relationship','reflection',x.context]}));(s.journal||[]).forEach(x=>out.push({id:`sig-journal-${x.id||hash(JSON.stringify(x))}`,at:x.at,domain:'journal',type:'entry',label:x.title||x.text?.slice(0,100)||'Journal entry',source:'private-chronicle',sourceId:x.id,context:{mood:x.mood||null},tags:['journal',...(x.tags||[])],privacy:'private',meta:{hasMedia:!!x.media?.length}}));return out}
function homeSignals(s){return (s.homeSystems||[]).filter(x=>x.last).map(x=>({id:stable('home-system',[x.id,x.last]),at:x.last,domain:'house',type:'maintenance',label:x.name,source:'home-systems',sourceId:x.id,context:{area:x.area,frequencyDays:x.freq,recurring:true},tags:['house',x.area,'maintenance']}))}
function iiSignals(){let d=read(II_KEY,{books:[],content:[],metrics:[]}),out=[];(d.books||[]).forEach((b,bi)=>{let bookId=b.id||`book-${slug(b.title)}-${bi}`;out.push({id:stable('ii-book',[bookId,b.current,b.target]),at:b.updatedAt||b.addedAt||new Date().toISOString(),domain:'reading',type:'reading-state',label:b.title,source:'ii-lab',sourceId:bookId,value:+b.current||0,unit:'page',context:{totalPages:+b.pages||0,target:b.target||null,remaining:Math.max(0,(+b.pages||0)-(+b.current||0))},tags:['reading','book']});(b.notes||[]).forEach((n,ni)=>out.push({id:stable('ii-note',[bookId,n.at,n.page,n.kind,n.text,ni]),at:n.at,domain:'reading',type:'note',label:n.text,source:'ii-lab',sourceId:`${bookId}:note:${ni}`,value:+n.page||0,unit:'page',context:{bookId,bookTitle:b.title,noteKind:n.kind},tags:['reading','note',n.kind,b.title]}))});(d.content||[]).forEach((c,i)=>out.push({id:stable('ii-content',[c.id||i,c.title,c.status,c.date]),at:c.date?`${c.date}T12:00:00`:c.at||new Date().toISOString(),domain:'publishing',type:'content',label:c.title,source:'ii-lab',sourceId:c.id||`content-${i}`,context:{contentType:c.type,status:c.status,bookId:c.bookId||null,bookTitle:c.bookTitle||null},tags:['publishing',c.type,c.status],links:c.bookId?[`book:${c.bookId}`]:[]}));(d.metrics||[]).forEach((m,i)=>out.push({id:stable('ii-metric',[m.at,m.name,i]),at:m.at,domain:'publishing',type:'performance-snapshot',label:m.name,source:'ii-lab',sourceId:m.id||`metric-${i}`,value:+m.views||0,unit:'views',context:{views:+m.views||0,likes:+m.likes||0,comments:+m.comments||0,saves:+m.saves||0,shares:+m.shares||0,contentId:m.contentId||null},tags:['publishing','metrics','performance']}));return out}
function autoLinks(signals){let links=[],books=signals.filter(x=>x.domain==='reading'&&x.type==='reading-state'),notes=signals.filter(x=>x.domain==='reading'&&x.type==='note'),content=signals.filter(x=>x.domain==='publishing'&&x.type==='content'),metrics=signals.filter(x=>x.domain==='publishing'&&x.type==='performance-snapshot');notes.forEach(n=>{let b=books.find(x=>x.sourceId===n.context.bookId);if(b)links.push({id:stable('link',[b.id,n.id]),from:b.id,to:n.id,relation:'produced-note',confidence:'explicit'})});content.forEach(c=>{let b=c.context.bookId&&books.find(x=>x.sourceId===c.context.bookId);if(!b&&c.context.bookTitle)b=books.find(x=>x.label===c.context.bookTitle);if(b)links.push({id:stable('link',[b.id,c.id]),from:b.id,to:c.id,relation:'informed-content',confidence:'explicit'})});metrics.forEach(m=>{let c=m.context.contentId&&content.find(x=>x.sourceId===m.context.contentId);if(!c)c=content.find(x=>x.label===m.label);if(c)links.push({id:stable('link',[c.id,m.id]),from:c.id,to:m.id,relation:'measured-by',confidence:'matched'})});return links}
function reconcile(){let s=state(),before=s.signals.length;[...(s.events||[]).map(eventSignal),...calendarSignals(s),...careSignals(s),...homeSignals(s),...iiSignals()].forEach(x=>upsert(s,x));let generated=autoLinks(s.signals);generated.forEach(l=>{let i=s.signalLinks.findIndex(x=>x.id===l.id);if(i<0)s.signalLinks.push(l);else s.signalLinks[i]={...s.signalLinks[i],...l}});s.integration={schema:SCHEMA,lastReconciled:new Date().toISOString(),signalCount:s.signals.length,linkCount:s.signalLinks.length,domains:[...new Set(s.signals.map(x=>x.domain))].sort()};save(s);window.dispatchEvent(new CustomEvent('lifeos:signals',{detail:s.integration}));return {...s.integration,added:s.signals.length-before}}
function emit(x){let s=state(),v=upsert(s,x);s.integration={...(s.integration||{}),schema:SCHEMA,lastSignalAt:v.at,signalCount:s.signals.length};save(s);window.dispatchEvent(new CustomEvent('lifeos:signal',{detail:v}));return v}
function query(q={}){let a=state().signals||[];if(q.domain)a=a.filter(x=>[].concat(q.domain).includes(x.domain));if(q.type)a=a.filter(x=>[].concat(q.type).includes(x.type));if(q.source)a=a.filter(x=>[].concat(q.source).includes(x.source));if(q.from)a=a.filter(x=>new Date(x.at)>=new Date(q.from));if(q.to)a=a.filter(x=>new Date(x.at)<=new Date(q.to));if(q.tag)a=a.filter(x=>x.tags.includes(slug(q.tag)));return a.sort((a,b)=>new Date(a.at)-new Date(b.at))}
function contextFor(dateLike,windowHours=12){let t=new Date(dateLike).getTime(),w=windowHours*3600000;return query().filter(x=>Math.abs(new Date(x.at).getTime()-t)<=w)}
function link(from,to,relation='related-to',confidence='explicit',meta={}){let s=state(),l={id:stable('link',[from,to,relation]),from,to,relation,confidence,meta,at:new Date().toISOString()},i=s.signalLinks.findIndex(x=>x.id===l.id);if(i<0)s.signalLinks.push(l);else s.signalLinks[i]=l;save(s);return l}
function stats(){let s=state(),byDomain={};(s.signals||[]).forEach(x=>byDomain[x.domain]=(byDomain[x.domain]||0)+1);return {signals:s.signals?.length||0,links:s.signalLinks?.length||0,domains:byDomain,lastReconciled:s.integration?.lastReconciled||null}}
window.LifeSignals={schema:SCHEMA,normalize,emit,reconcile,query,contextFor,link,stats};
reconcile();document.addEventListener('visibilitychange',()=>{if(!document.hidden)reconcile()});window.addEventListener('focus',reconcile);setInterval(reconcile,15000);
})();