/* Dre After Dark · Life OS — Unified Signal / Integration Layer */
(()=>{
const OS_KEY='dreLifeOS',II_KEY='dreLifeOS_ii',SCHEMA=2;
const read=(k,f={})=>{try{return JSON.parse(localStorage.getItem(k)||'null')||f}catch{return f}},write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const uid=()=>crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random()}`,iso=v=>{try{return new Date(v||Date.now()).toISOString()}catch{return new Date().toISOString()}},day=v=>iso(v).slice(0,10),text=v=>String(v??'').trim(),slug=v=>text(v).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,80)||'item';
const hash=s=>{let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return(h>>>0).toString(36)},stable=(source,parts)=>`sig-${source}-${hash(parts.map(text).join('|'))}`;
function state(){let s=read(OS_KEY,{events:[]});s.events=s.events||[];s.signals=s.signals||[];s.signalLinks=s.signalLinks||[];s.integration=s.integration||{};return s}function save(s){write(OS_KEY,s)}
function normalize(x={}){return{id:x.id||uid(),schema:SCHEMA,at:iso(x.at),day:day(x.at),domain:text(x.domain)||'life',type:text(x.type)||'observation',label:text(x.label||x.detail||x.type),value:x.value??null,unit:text(x.unit)||null,source:text(x.source)||'life-os',sourceId:text(x.sourceId)||null,energy:text(x.energy)||null,context:x.context&&typeof x.context==='object'?x.context:{},tags:[...new Set((x.tags||[]).map(slug).filter(Boolean))],links:[...new Set((x.links||[]).filter(Boolean))],privacy:x.privacy||'private',evidence:x.evidence||'observation',meta:x.meta&&typeof x.meta==='object'?x.meta:{}}}function upsert(s,x){x=normalize(x);let i=s.signals.findIndex(v=>v.id===x.id);if(i<0)s.signals.push(x);else s.signals[i]={...s.signals[i],...x};return x}
function eventSignal(e){let sid=e.id||stable('event',[e.at,e.domain,e.type,e.detail]);return{id:`sig-event-${sid}`,at:e.at,domain:e.domain||'life',type:e.type||'event',label:e.detail||e.type,source:'life-events',sourceId:sid,energy:e.energy||null,value:e.amount??e.count??null,context:{calendarRelated:e.domain==='calendar',householdRelated:['house','plant'].includes(e.domain),behavioral:true},tags:[e.domain,e.type],meta:{rawEventId:e.id||null}}}
const CAL_RULES=[
 {kind:'healthcare',words:['doctor','dr ','dentist','dental','derm','dermat','therapy','therapist','psychi','clinic','medical','appointment','pa-c','physician','lab','blood','vision','optom'],tags:['health','care'],load:2},
 {kind:'work',words:['1-on-1','1:1','meeting','supervisor','work','training','conference','webinar','interview','office'],tags:['work','obligation'],load:2},
 {kind:'academic',words:['class','mba','assignment','discussion','paper','exam','school','uopeople','capstone','graduation'],tags:['academic','cognitive'],load:2},
 {kind:'social',words:['wedding','party','dinner','brunch','friend','birthday','concert','event'],tags:['social'],load:2},
 {kind:'finance-admin',words:['pay day','payday','payment','bill','insurance','credit','due','renew','dmv','bank'],tags:['finance','admin'],load:1},
 {kind:'reading-publishing',words:['read','reading','book','review','publish','post','reel','ink & intrigue','i&i'],tags:['reading','creative'],load:1},
 {kind:'self-care',words:['nail','hair','salon','spa','beauty'],tags:['vanity','self-care'],load:1},
 {kind:'household',words:['clean','trash','house','dog','grocery','plant','water'],tags:['household'],load:1}
];
function semanticCalendar(e){let title=text(e.title),low=title.toLowerCase(),start=new Date(e.start),end=e.end?new Date(e.end):null,duration=end&&isFinite(end)?Math.max(0,Math.round((end-start)/60000)):e.allDay?1440:null,rule=CAL_RULES.find(r=>r.words.some(w=>low.includes(w)))||{kind:'unspecified',tags:['uncategorized'],load:1};let h=start.getHours(),part=e.allDay?'all-day':h<6?'early-morning':h<12?'morning':h<17?'midday':h<21?'evening':'night',weekend=[0,6].includes(start.getDay()),workHours=!e.allDay&&!weekend&&h>=7&&h<17,evening=!e.allDay&&h>=17&&h<22,early=!e.allDay&&h<7;let disruption=rule.load+(e.allDay?0:duration>=120?2:duration>=60?1:0)+(early||evening?1:0);return{kind:rule.kind,semanticTags:rule.tags,timeOfDay:part,durationMinutes:duration,weekend,weekday:!weekend,workHours,evening,earlyMorning:early,scheduledInterruption:!e.allDay,loadBand:disruption>=4?'high':disruption>=2?'moderate':'light',loadScore:disruption}}
function calendarSignals(s){return(s.calendar?.events||[]).map(e=>{let sem=semanticCalendar(e);return{id:stable('calendar',[e.id,e.start]),at:e.start,domain:'calendar',type:'scheduled-event',label:e.title,source:'google-calendar',sourceId:e.id,context:{end:e.end||null,allDay:!!e.allDay,status:e.status||null,scheduled:true,...sem},tags:['calendar','schedule',e.allDay?'all-day':'timed',sem.kind,sem.timeOfDay,...sem.semanticTags],links:e.htmlLink?[e.htmlLink]:[],meta:{semanticVersion:1}}})}
function careSignals(s){let out=[];(s.health||[]).forEach(x=>out.push({id:`sig-health-${x.id||hash(JSON.stringify(x))}`,at:x.at,domain:'health',type:x.kind||'observation',label:x.note,source:'care-dossier',sourceId:x.id,context:{area:x.area,hypothesis:x.hypothesis||null,clinicianQuestion:x.question||null},tags:['health',x.area,x.kind],links:x.link?[x.link]:[],evidence:'observation'}));(s.relationship||[]).forEach(x=>out.push({id:`sig-relationship-${x.id||hash(JSON.stringify(x))}`,at:x.at,domain:'relationship',type:'reflection',label:x.event,source:'relationship-self-study',sourceId:x.id,context:{relationshipContext:x.context,interpretation:x.interpretation,response:x.response,need:x.need,nextExperiment:x.next},tags:['relationship','reflection',x.context]}));(s.journal||[]).forEach(x=>out.push({id:`sig-journal-${x.id||hash(JSON.stringify(x))}`,at:x.at,domain:'journal',type:'entry',label:x.title||x.text?.slice(0,100)||'Journal entry',source:'private-chronicle',sourceId:x.id,context:{mood:x.mood||null},tags:['journal',...(x.tags||[])],privacy:'private',meta:{hasMedia:!!x.media?.length}}));return out}
function homeSignals(s){return(s.homeSystems||[]).filter(x=>x.last).map(x=>({id:stable('home-system',[x.id,x.last]),at:x.last,domain:'house',type:'maintenance',label:x.name,source:'home-systems',sourceId:x.id,context:{area:x.area,frequencyDays:x.freq,recurring:true},tags:['house',x.area,'maintenance']}))}
function iiSignals(){let d=read(II_KEY,{books:[],content:[],metrics:[]}),out=[];(d.books||[]).forEach((b,bi)=>{let bookId=b.id||`book-${slug(b.title)}-${bi}`;out.push({id:stable('ii-book',[bookId,b.current,b.target]),at:b.updatedAt||b.addedAt||new Date().toISOString(),domain:'reading',type:'reading-state',label:b.title,source:'ii-lab',sourceId:bookId,value:+b.current||0,unit:'page',context:{totalPages:+b.pages||0,target:b.target||null,remaining:Math.max(0,(+b.pages||0)-(+b.current||0))},tags:['reading','book']});(b.notes||[]).forEach((n,ni)=>out.push({id:stable('ii-note',[bookId,n.at,n.page,n.kind,n.text,ni]),at:n.at,domain:'reading',type:'note',label:n.text,source:'ii-lab',sourceId:`${bookId}:note:${ni}`,value:+n.page||0,unit:'page',context:{bookId,bookTitle:b.title,noteKind:n.kind},tags:['reading','note',n.kind,b.title]}))});(d.content||[]).forEach((c,i)=>out.push({id:stable('ii-content',[c.id||i,c.title,c.status,c.date]),at:c.date?`${c.date}T12:00:00`:c.at||new Date().toISOString(),domain:'publishing',type:'content',label:c.title,source:'ii-lab',sourceId:c.id||`content-${i}`,context:{contentType:c.type,status:c.status,bookId:c.bookId||null,bookTitle:c.bookTitle||null},tags:['publishing',c.type,c.status]}));(d.metrics||[]).forEach((m,i)=>out.push({id:stable('ii-metric',[m.at,m.name,i]),at:m.at,domain:'publishing',type:'performance-snapshot',label:m.name,source:'ii-lab',sourceId:m.id||`metric-${i}`,value:+m.views||0,unit:'views',context:{views:+m.views||0,likes:+m.likes||0,comments:+m.comments||0,saves:+m.saves||0,shares:+m.shares||0,contentId:m.contentId||null},tags:['publishing','metrics','performance']}));return out}
function autoLinks(signals){let links=[],books=signals.filter(x=>x.domain==='reading'&&x.type==='reading-state'),notes=signals.filter(x=>x.domain==='reading'&&x.type==='note'),content=signals.filter(x=>x.domain==='publishing'&&x.type==='content'),metrics=signals.filter(x=>x.domain==='publishing'&&x.type==='performance-snapshot');notes.forEach(n=>{let b=books.find(x=>x.sourceId===n.context.bookId);if(b)links.push({id:stable('link',[b.id,n.id]),from:b.id,to:n.id,relation:'produced-note',confidence:'explicit'})});content.forEach(c=>{let b=c.context.bookId&&books.find(x=>x.sourceId===c.context.bookId);if(!b&&c.context.bookTitle)b=books.find(x=>x.label===c.context.bookTitle);if(b)links.push({id:stable('link',[b.id,c.id]),from:b.id,to:c.id,relation:'informed-content',confidence:'explicit'})});metrics.forEach(m=>{let c=m.context.contentId&&content.find(x=>x.sourceId===m.context.contentId);if(!c)c=content.find(x=>x.label===m.label);if(c)links.push({id:stable('link',[c.id,m.id]),from:c.id,to:m.id,relation:'measured-by',confidence:'matched'})});return links}
function calendarContext(signals){let cal=signals.filter(x=>x.domain==='calendar'&&x.type==='scheduled-event'),behavior=signals.filter(x=>x.domain!=='calendar');let links=[];cal.forEach(c=>{let ct=new Date(c.at).getTime(),end=c.context.end?new Date(c.context.end).getTime():ct;behavior.forEach(b=>{let bt=new Date(b.at).getTime(),delta=(bt-ct)/3600000;if(bt>=ct-6*3600000&&bt<=end+18*3600000)links.push({id:stable('link',[c.id,b.id,'calendar-context']),from:c.id,to:b.id,relation:'calendar-context',confidence:'temporal',meta:{hoursFromStart:+delta.toFixed(1),calendarKind:c.context.kind,loadBand:c.context.loadBand}})})});return links}
function reconcile(){let s=state(),before=s.signals.length;[...(s.events||[]).map(eventSignal),...calendarSignals(s),...careSignals(s),...homeSignals(s),...iiSignals()].forEach(x=>upsert(s,x));let generated=[...autoLinks(s.signals),...calendarContext(s.signals)];generated.forEach(l=>{let i=s.signalLinks.findIndex(x=>x.id===l.id);if(i<0)s.signalLinks.push(l);else s.signalLinks[i]={...s.signalLinks[i],...l}});s.integration={schema:SCHEMA,lastReconciled:new Date().toISOString(),signalCount:s.signals.length,linkCount:s.signalLinks.length,domains:[...new Set(s.signals.map(x=>x.domain))].sort()};save(s);window.dispatchEvent(new CustomEvent('lifeos:signals',{detail:s.integration}));return{...s.integration,added:s.signals.length-before}}
function emit(x){let s=state(),v=upsert(s,x);save(s);return v}function query(q={}){let a=state().signals||[];if(q.domain)a=a.filter(x=>[].concat(q.domain).includes(x.domain));if(q.type)a=a.filter(x=>[].concat(q.type).includes(x.type));if(q.source)a=a.filter(x=>[].concat(q.source).includes(x.source));if(q.from)a=a.filter(x=>new Date(x.at)>=new Date(q.from));if(q.to)a=a.filter(x=>new Date(x.at)<=new Date(q.to));if(q.tag)a=a.filter(x=>x.tags.includes(slug(q.tag)));return a.sort((a,b)=>new Date(a.at)-new Date(b.at))}function contextFor(dateLike,windowHours=12){let t=new Date(dateLike).getTime(),w=windowHours*3600000;return query().filter(x=>Math.abs(new Date(x.at).getTime()-t)<=w)}function stats(){let s=state(),byDomain={};(s.signals||[]).forEach(x=>byDomain[x.domain]=(byDomain[x.domain]||0)+1);return{signals:s.signals?.length||0,links:s.signalLinks?.length||0,domains:byDomain,lastReconciled:s.integration?.lastReconciled||null}}
function calendarProfile(){let s=state(),cal=(s.signals||[]).filter(x=>x.domain==='calendar'&&x.type==='scheduled-event'),links=s.signalLinks||[],kinds={},loads={light:0,moderate:0,high:0};cal.forEach(c=>{kinds[c.context.kind]=(kinds[c.context.kind]||0)+1;loads[c.context.loadBand]=(loads[c.context.loadBand]||0)+1});let contextualized=new Set(links.filter(l=>l.relation==='calendar-context').map(l=>l.from)).size;return{events:cal.length,kinds,loads,contextualized,contextLinks:links.filter(l=>l.relation==='calendar-context').length}}
window.LifeSignals={schema:SCHEMA,normalize,emit,reconcile,query,contextFor,stats,semanticCalendar,calendarProfile};reconcile();document.addEventListener('visibilitychange',()=>{if(!document.hidden)reconcile()});window.addEventListener('focus',reconcile);setInterval(reconcile,15000);
})();