/* Dre After Dark · Life OS — Kitchen Command */
(()=>{'use strict';const K='dreLifeOS',$=s=>document.querySelector(s),uid=()=>crypto.randomUUID?.()||Date.now()+'-'+Math.random(),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function read(){try{let d=window.LifeStore?.read?.()||JSON.parse(localStorage.getItem(K)||'{}');d.kitchen=d.kitchen||{};['mealPrep','pantry','leftovers','groceries','recipes'].forEach(k=>d.kitchen[k]=d.kitchen[k]||[]);return d}catch{return{kitchen:{mealPrep:[],pantry:[],leftovers:[],groceries:[],recipes:[]}}}}
function save(d){if(window.LifeStore?.mutate){let k=d.kitchen;LifeStore.mutate(cur=>{cur.kitchen=k;return cur},'kitchen-command')}else localStorage.setItem(K,JSON.stringify(d));render()}
const defs={mealPrep:['🥘','Meal Prep','Meal / batch','Portions / plan'],pantry:['🥫','Pantry','Item','Quantity / location'],leftovers:['🧊','Leftovers','Food','Use by / note'],groceries:['🛒','Groceries','Item','Quantity / note'],recipes:['📖','Recipes','Recipe','Link / notes']};
function add(kind){let d=read(),name=$('[data-k-name="'+kind+'"]')?.value.trim(),note=$('[data-k-note="'+kind+'"]')?.value.trim();if(!name)return;d.kitchen[kind].push({id:uid(),at:new Date().toISOString(),name,note,done:false});save(d);render()}
function toggle(kind,id){let d=read(),x=d.kitchen[kind].find(v=>v.id===id);if(!x)return;x.done=!x.done;save(d);render()}
function del(kind,id){let d=read();d.kitchen[kind]=d.kitchen[kind].filter(v=>v.id!==id);save(d);render()}
function card(kind){let [icon,title,p1,p2]=defs[kind],a=read().kitchen[kind];return `<article class="card"><p class="eyebrow">${icon} ${title.toUpperCase()}</p><h3>${title}</h3><div class="row"><input data-k-name="${kind}" placeholder="${p1}"><input data-k-note="${kind}" placeholder="${p2}"></div><button data-k-add="${kind}">+ Add</button><p class="quiet">${a.length} saved</p>${a.slice().reverse().slice(0,12).map(x=>`<div class="ii-item"><div><b>${x.done?'✓ ':''}${esc(x.name)}</b></div>${x.note?`<small>${esc(x.note)}</small>`:''}<div class="row"><button data-k-toggle="${kind}|${x.id}">${x.done?'Reopen':'Done'}</button><button class="ghost" data-k-delete="${kind}|${x.id}">Delete</button></div></div>`).join('')}</article>`}
function render(){let h=$('#kitchenCommand');if(!h)return;let d=read(),prep=d.kitchen.mealPrep.filter(x=>!x.done).length,grocery=d.kitchen.groceries.filter(x=>!x.done).length,left=d.kitchen.leftovers.filter(x=>!x.done).length;h.innerHTML=`<article class="card accent"><p class="eyebrow">KITCHEN COMMAND</p><div class="conservatory-strip"><div><strong>${prep}</strong><small>prep items</small></div><div><strong>${grocery}</strong><small>groceries</small></div><div><strong>${left}</strong><small>leftovers</small></div><div><strong>${d.kitchen.recipes.length}</strong><small>recipes</small></div></div></article><div class="grid two">${Object.keys(defs).map(card).join('')}</div>`;h.querySelectorAll('[data-k-add]').forEach(b=>b.onclick=()=>add(b.dataset.kAdd));h.querySelectorAll('[data-k-toggle]').forEach(b=>b.onclick=()=>{let [k,id]=b.dataset.kToggle.split('|');toggle(k,id)});h.querySelectorAll('[data-k-delete]').forEach(b=>b.onclick=()=>{let [k,id]=b.dataset.kDelete.split('|');del(k,id)})}
document.addEventListener('click',e=>{if(e.target.closest?.('#nav [data-view="kitchen"]'))setTimeout(render,60)},true);window.addEventListener('lifeos:data-changed',()=>{if($('#kitchen')?.classList.contains('active'))setTimeout(render,20)});if($('#kitchen')?.classList.contains('active'))render();window.KitchenCommand={render};})();