/* Dre After Dark · Life OS — Kitchen Command V2 */
(()=>{'use strict';const K='dreLifeOS',$=s=>document.querySelector(s),uid=()=>crypto.randomUUID?.()||Date.now()+'-'+Math.random(),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function read(){try{let d=window.LifeStore?.read?.()||JSON.parse(localStorage.getItem(K)||'{}');d.kitchen=d.kitchen||{};['mealPrep','pantry','leftovers','groceries','recipes'].forEach(k=>d.kitchen[k]=d.kitchen[k]||[]);return d}catch{return{kitchen:{mealPrep:[],pantry:[],leftovers:[],groceries:[],recipes:[]}}}}
function save(d){if(window.LifeStore?.mutate){let k=d.kitchen;LifeStore.mutate(cur=>{cur.kitchen=k;return cur},'kitchen-command')}else localStorage.setItem(K,JSON.stringify(d))}
const meta={mealPrep:{icon:'🥘',title:'Meal Prep',sub:'Plan batches and portions for the week.'},pantry:{icon:'🥫',title:'Pantry',sub:'Know what you have and what needs using.'},leftovers:{icon:'🧊',title:'Leftovers',sub:'Use food before it becomes archaeology.'},groceries:{icon:'🛒',title:'Groceries',sub:'A practical shopping list, not another note.'},recipes:{icon:'📖',title:'Recipes',sub:'Keep repeatable meals and their instructions.'}};
function fields(k){if(k==='mealPrep')return '<input data-f="name" placeholder="Meal / batch"><input data-f="servings" type="number" min="1" placeholder="Servings"><select data-f="meal"><option value="">Meal</option><option>Breakfast</option><option>Lunch</option><option>Dinner</option><option>Snack</option></select><input data-f="date" type="date" aria-label="Prep date"><textarea data-f="note" placeholder="Ingredients, portions, prep notes…"></textarea>';if(k==='pantry')return '<input data-f="name" placeholder="Pantry item"><input data-f="qty" placeholder="Quantity"><select data-f="location"><option>Pantry</option><option>Fridge</option><option>Freezer</option><option>Other</option></select><input data-f="date" type="date" aria-label="Best by date"><textarea data-f="note" placeholder="Brand, opened date, notes…"></textarea>';if(k==='leftovers')return '<input data-f="name" placeholder="Leftover / prepared food"><input data-f="qty" placeholder="Portions"><input data-f="date" type="date" aria-label="Use by date"><textarea data-f="note" placeholder="Storage / reheating note…"></textarea>';if(k==='groceries')return '<input data-f="name" placeholder="Grocery item"><input data-f="qty" placeholder="Quantity"><select data-f="location"><option>Produce</option><option>Meat / Seafood</option><option>Dairy</option><option>Pantry</option><option>Frozen</option><option>Household</option><option>Other</option></select><textarea data-f="note" placeholder="Brand, size, store, note…"></textarea>';return '<input data-f="name" placeholder="Recipe name"><input data-f="source" placeholder="Source / link"><textarea data-f="ingredients" placeholder="Ingredients"></textarea><textarea data-f="instructions" placeholder="Instructions"></textarea><textarea data-f="note" placeholder="Changes, rating, serving notes…"></textarea>'}
function add(k,card){let d=read(),x={id:uid(),at:new Date().toISOString(),done:false};card.querySelectorAll('[data-f]').forEach(el=>x[el.dataset.f]=String(el.value??'').trim());if(!x.name)return;d.kitchen[k].push(x);save(d);render()}
function toggle(k,id){let d=read(),x=d.kitchen[k].find(v=>v.id===id);if(!x)return;x.done=!x.done;save(d);render()}
function del(k,id){if(!confirm('Delete this Kitchen record?'))return;let d=read();d.kitchen[k]=d.kitchen[k].filter(v=>v.id!==id);save(d);render()}
function detail(k,x){let bits=[];if(x.servings)bits.push(x.servings+' servings');if(x.meal)bits.push(x.meal);if(x.qty)bits.push(x.qty);if(x.location)bits.push(x.location);if(x.date)bits.push((k==='leftovers'?'use by ':k==='pantry'?'best by ':k==='mealPrep'?'prep ':'')+x.date);if(x.source)bits.push(x.source);return bits}
function item(k,x){let bits=detail(k,x);return `<div class="ii-item kitchen-item ${x.done?'kitchen-done':''}"><div><b>${x.done?'✓ ':''}${esc(x.name)}</b></div>${bits.length?'<small>'+bits.map(esc).join(' · ')+'</small>':''}${x.ingredients?'<p><b>Ingredients:</b> '+esc(x.ingredients)+'</p>':''}${x.instructions?'<p><b>Instructions:</b> '+esc(x.instructions)+'</p>':''}${x.note?'<small>'+esc(x.note)+'</small>':''}<div class="row kitchen-item-actions">${k!=='recipes'?'<button data-k-toggle="'+k+'|'+x.id+'">'+(x.done?'Reopen':'Done')+'</button>':''}<button class="ghost" data-k-delete="${k}|${x.id}">Delete</button></div></div>`}
function card(k,d){let m=meta[k],a=d.kitchen[k];return `<article class="card kitchen-card" data-k-card="${k}"><p class="eyebrow">${m.icon} ${m.title.toUpperCase()}</p><h3>${m.title}</h3><p class="quiet">${m.sub}</p><div class="kitchen-fields">${fields(k)}</div><button data-k-add="${k}">+ Save ${m.title.replace(/s$/,'')}</button><p class="quiet">${a.length} saved</p><div class="kitchen-records">${a.slice().reverse().slice(0,20).map(x=>item(k,x)).join('')}</div></article>`}
function render(){let h=$('#kitchenCommand');if(!h)return;let d=read(),prep=d.kitchen.mealPrep.filter(x=>!x.done).length,grocery=d.kitchen.groceries.filter(x=>!x.done).length,left=d.kitchen.leftovers.filter(x=>!x.done).length,exp=d.kitchen.leftovers.filter(x=>!x.done&&x.date&&new Date(x.date+'T23:59:59')<new Date()).length;h.innerHTML=`<article class="card accent"><p class="eyebrow">KITCHEN COMMAND · V2</p><h3>What's happening in the kitchen?</h3><div class="conservatory-strip"><div><strong>${prep}</strong><small>prep plans</small></div><div><strong>${grocery}</strong><small>to buy</small></div><div><strong>${left}</strong><small>leftovers</small></div><div><strong>${exp}</strong><small>past use-by</small></div></div></article><div class="grid two">${Object.keys(meta).map(k=>card(k,d)).join('')}</div>`;h.querySelectorAll('[data-k-add]').forEach(b=>b.onclick=()=>add(b.dataset.kAdd,b.closest('[data-k-card]')));h.querySelectorAll('[data-k-toggle]').forEach(b=>b.onclick=()=>{let [k,id]=b.dataset.kToggle.split('|');toggle(k,id)});h.querySelectorAll('[data-k-delete]').forEach(b=>b.onclick=()=>{let [k,id]=b.dataset.kDelete.split('|');del(k,id)})}
document.addEventListener('click',e=>{if(e.target.closest?.('#nav [data-view="kitchen"]'))setTimeout(render,60)},true);window.addEventListener('lifeos:data-changed',()=>{if($('#kitchen')?.classList.contains('active'))setTimeout(render,20)});function boot(){render()}document.readyState==='loading'?document.addEventListener('DOMContentLoaded',boot,{once:true}):boot();window.KitchenCommand={render};})();