/* Dre After Dark · Life OS — Personal Labs + Smart Scanner */
(()=>{'use strict';const K='dreLifeOS_personalLabs',$=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m])),load=()=>{try{return JSON.parse(localStorage.getItem(K)||'{}')}catch{return{}}},save=d=>localStorage.setItem(K,JSON.stringify(d));
const labs=[
{id:'skin',icon:'✨',name:'Skincare Lab',desc:'AM/PM routines, products, treatments, photos, reactions and progress.',fields:['AM routine','PM routine','Treatment / device','Observation']},
{id:'hair',icon:'💇🏿‍♀️',name:'Hair Lab',desc:'Wash days, scalp care, products, treatments, protective styles, trims, shedding, length and density.',fields:['Wash / treatment','Scalp / shedding','Style / tension','Length / density note']},
{id:'body',icon:'🥗',name:'Body + Nutrition Lab',desc:'Meals, hydration, meal prep, nutrients, measurements and body observations.',fields:['Meal / prep','Hydration','Nutrition note','Measurement / observation']},
{id:'kitchen',icon:'🍳',name:'Pantry + Kitchen Oracle',desc:'Inventory, leftovers, recipes and what-to-make-next notes.',fields:['Pantry item','Leftover / expiry','Recipe idea','Prep note']},
{id:'beauty',icon:'💄',name:'Beauty Cabinet',desc:'Makeup, shade notes, looks, tools, nails and event-ready combinations.',fields:['Product / shade','Look','Tool / brush','Result / wear note']}
];
function addLog(id){let d=load(),v=prompt('What do you want to record?');if(!v)return;(d[id]??=[]).push({at:new Date().toISOString(),text:v});save(d);render()}
function photo(id,input){let f=input.files?.[0];if(!f)return;let r=new FileReader();r.onload=()=>{let d=load();(d.photos??=[]).push({id,at:new Date().toISOString(),name:f.name,data:r.result});save(d);render()};r.readAsDataURL(f)}
function render(){let h=$('#personalLabs');if(!h)return,d=load();h.innerHTML=`<div class="sectionhead"><div><p class="eyebrow">THE VANITY · BODY · KITCHEN</p><h2>Personal Labs</h2><p>Track change over time instead of relying on memory.</p></div></div><div class="grid two">${labs.map(l=>{let logs=d[l.id]||[],pics=(d.photos||[]).filter(p=>p.id===l.id);return`<article class="card"><p class="eyebrow">${l.icon} ${esc(l.name).toUpperCase()}</p><h3>${esc(l.name)}</h3><p>${esc(l.desc)}</p><small>${l.fields.map(esc).join(' · ')}</small><div class="row"><button data-log="${l.id}">+ Log</button><label class="file">📸 Progress photo<input data-photo="${l.id}" type="file" accept="image/*" capture="environment"></label></div>${pics.at(-1)?`<img src="${pics.at(-1).data}" alt="Latest ${esc(l.name)} progress" style="width:100%;max-height:220px;object-fit:cover;border-radius:14px;margin-top:12px">`:''}<p class="quiet">${logs.length} logs · ${pics.length} photos</p>${logs.slice(-3).reverse().map(x=>`<div class="ii-item"><small>${new Date(x.at).toLocaleDateString()} · ${esc(x.text)}</small></div>`).join('')}</article>`}).join('')}</div>`;h.querySelectorAll('[data-log]').forEach(b=>b.onclick=()=>addLog(b.dataset.log));h.querySelectorAll('[data-photo]').forEach(i=>i.onchange=()=>photo(i.dataset.photo,i))}
function scanner(){let h=$('#smartScanner');if(!h)return;h.innerHTML=`<article class="card accent"><p class="eyebrow">📷 SMART SCANNER + PICTURE DESK</p><h3>Capture first. Identify second.</h3><p>Photograph or upload a product, plant, skin/hair progress image, receipt, book, label, pantry item or other object and file it into the right Life OS lab.</p><input id="smartScanInput" type="file" accept="image/*" capture="environment"><select id="smartScanDest"><option value="skin">Skin</option><option value="hair">Hair</option><option value="beauty">Beauty</option><option value="kitchen">Kitchen</option><option value="plants">Conservatory</option><option value="other">Other</option></select><textarea id="smartScanNote" placeholder="What is this / what should Life OS remember?"></textarea><button id="smartScanSave">Save scan</button><p class="quiet"><b>Recognition status:</b> capture, preview and classification are active. Automated visual identification requires a vision service/backend; Life OS will not pretend a filename is AI recognition.</p><div id="scanPreview"></div></article>`;let inp=$('#smartScanInput');inp.onchange=()=>{let f=inp.files?.[0];if(!f)return,r=new FileReader();r.onload=()=>$('#scanPreview').innerHTML=`<img src="${r.result}" style="width:100%;max-height:300px;object-fit:contain;border-radius:14px;margin-top:12px">`;r.readAsDataURL(f)};$('#smartScanSave').onclick=()=>{let f=inp.files?.[0];if(!f)return alert('Choose a picture first.');let r=new FileReader();r.onload=()=>{let d=load();(d.scans??=[]).push({at:new Date().toISOString(),dest:$('#smartScanDest').value,note:$('#smartScanNote').value,name:f.name,data:r.result});save(d);alert('Scan filed in Life OS.');render()};r.readAsDataURL(f)}}
function install(){let settings=$('#settings');if(!settings)return false;let h=$('#personalLabs');if(!h){h=document.createElement('div');h.id='personalLabs';settings.prepend(h)}let s=$('#smartScanner');if(!s){s=document.createElement('div');s.id='smartScanner';settings.prepend(s)}scanner();render();return true}function boot(){let n=0,t=setInterval(()=>{if(install()||++n>30)clearInterval(t)},200)}document.readyState==='loading'?document.addEventListener('DOMContentLoaded',boot,{once:true}):boot();})();