/* Dre After Dark · Life OS — Operating Manual v2 */
(()=>{'use strict';
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const sections=['Initiation Architecture','Recovery Architecture','Schedule Sensitivity','Cognitive & Creative Conditions','Domestic Environment','Reading & Intellectual Production','Leisure Ecology','Social & Relationship Patterns','Body & Care Context','Sleep / Wake Architecture','What Helps','What Apparently Does Not'];
const rank=m=>{m=String(m||'').toLowerCase();return /established|repeated|experiment evidence/.test(m)?3:/developing|emerging|early/.test(m)?2:/learning|investigation|insufficient|single/.test(m)?1:0};
const label=m=>rank(m)>=3?'ESTABLISHED':rank(m)===2?'EMERGING':rank(m)===1?'LEARNING':'UNDER INVESTIGATION';
function model(){
 let insight=window.InsightEngine?.model?.()||{insights:[]},recovery=window.RecoveryEngine?.summary?.()||{},experiments=window.ExperimentEngine?.all?.()||[],signals=window.LifeSignals?.query?.()||[],items=[];
 const add=x=>items.push({...x,level:rank(x.maturity)});
 (insight.insights||[]).forEach(x=>add({section:x.class==='schedule'?'Schedule Sensitivity':x.class==='body-environment'?'Body & Care Context':'Initiation Architecture',claim:x.text,maturity:x.confidence||'under investigation',evidence:x.evidence||{},source:'Insight Engine',why:x.why||''}));
 if(recovery.recovered){let raw=recovery.interventions||[],total=raw.reduce((n,x)=>n+x.n,0),weighted=total?raw.reduce((n,x)=>n+x.avgHours*x.n,0)/total:null,latency=weighted==null?'—':weighted<1?Math.round(weighted*60)+' minutes':(+weighted.toFixed(1))+' hours';add({section:'Recovery Architecture',claim:`Across ${recovery.recovered} measured recoveries, average recorded recovery latency is ${latency}.`,maturity:recovery.status,evidence:{episodes:recovery.episodes,recovered:recovery.recovered},source:'Recovery Intelligence'});raw.filter(x=>x.n>=2).forEach(x=>add({section:'What Helps',claim:`“${x.name}” has ${x.n} measured recoveries averaging ${x.avgHours<1?Math.round(x.avgHours*60)+' minutes':x.avgHours+' hours'}.`,maturity:x.evidence||recovery.status,evidence:{n:x.n,avgHours:x.avgHours},source:'Recovery Intelligence'}))}
 experiments.filter(x=>['completed','inconclusive'].includes(x.status)).forEach(x=>{let j=x.result?.systemConclusion?.judgment||'inconclusive',section=j==='weaken'?'What Apparently Does Not':'What Helps',why=x.result?.systemConclusion?.why||x.result?.interpretation||x.status,conf=x.result?.systemConclusion?.confidence||'low';add({section,claim:`Experiment “${x.title}”: ${why}`,maturity:j==='inconclusive'?'under investigation':conf==='high'?'experiment evidence':'emerging',evidence:x.result||{},source:'Experiment Engine'})});
 let reading=signals.filter(x=>x.domain==='reading').length,publishing=signals.filter(x=>x.domain==='publishing').length;if(reading||publishing)add({section:'Reading & Intellectual Production',claim:`${reading} reading signals and ${publishing} publishing/performance signals are available for production-chain analysis.`,maturity:reading+publishing>=20?'developing':'under investigation',evidence:{reading,publishing},source:'Unified Signals'});
 let grouped=sections.map(name=>({name,items:items.filter(x=>x.section===name).sort((a,b)=>b.level-a.level)}));
 return{generatedAt:new Date().toISOString(),signals:signals.length,sections:grouped,experiments:{running:experiments.filter(x=>x.status==='running').length,total:experiments.length},counts:{established:items.filter(x=>x.level===3).length,emerging:items.filter(x=>x.level===2).length,learning:items.filter(x=>x.level===1).length}};
}
function render(root){let m=model(),informed=m.sections.filter(x=>x.items.length);root.innerHTML=`<section class="profile-cover card"><p class="eyebrow">SUBJECT DRE · LIVING DOCUMENT</p><h2>The Operating Manual</h2><p class="profile-deck">What Life OS has actually learned about how you function. Claims strengthen, weaken, or disappear as evidence changes.</p><div class="metrics"><div><strong>${m.signals}</strong><span>&nbsp;signals</span></div><div><strong>${informed.length}/${m.sections.length}</strong><span>&nbsp;chapters informed</span></div><div><strong>${m.counts.established}</strong><span>&nbsp;established</span></div><div><strong>${m.counts.emerging}</strong><span>&nbsp;emerging</span></div></div><p class="quiet">Evidence ladder: Under investigation → Learning → Emerging → Established. Empty chapters remain empty rather than becoming invented traits.</p></section>${m.sections.map(s=>`<article class="card"><div class="sectionhead"><div><p class="eyebrow">${esc(s.name.toUpperCase())}</p><h3>${s.items.length?s.items.length+' evidence-backed '+(s.items.length===1?'finding':'findings'):'Still learning'}</h3></div></div>${s.items.length?s.items.map((x,i)=>`<div class="care-note"><p class="eyebrow">${label(x.maturity)}</p><p>${esc(x.claim)}</p><div class="row"><small>${esc(x.source)} · revisable</small><button class="ghost" data-manual-detail="${esc(s.name)}|${i}">Why?</button></div></div>`).join(''):'<p class="quiet">Life OS does not have enough evidence to write this chapter yet.</p>'}</article>`).join('')}`;root.querySelectorAll('[data-manual-detail]').forEach(b=>b.onclick=()=>{let [name,i]=b.dataset.manualDetail.split('|'),x=model().sections.find(s=>s.name===name)?.items[+i];if(!x)return;let modal=document.querySelector('#modal'),c=document.querySelector('#modalContent');if(c)c.innerHTML=`<p class="eyebrow">EVIDENCE TRACE</p><h2>${esc(name)}</h2><p><b>${label(x.maturity)}</b></p><p>${esc(x.claim)}</p><h3>Why Life OS says this</h3><p>${esc(x.why||'This statement is generated from the source and evidence shown below.')}</p><p><b>Source:</b> ${esc(x.source)}</p><pre style="white-space:pre-wrap;font-size:.8rem">${esc(JSON.stringify(x.evidence||{},null,2))}</pre><p class="quiet">This is a revisable inference, not a permanent trait label.</p>`;modal?.classList.remove('hidden')})}
function activate(s,b){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));document.querySelectorAll('#nav button').forEach(x=>x.classList.remove('active'));s.classList.add('active');b.classList.add('active');try{localStorage.setItem('dreLifeOS_activeView','operatingManual')}catch{}render(s.querySelector('#operatingManualRoot'))}
function install(){let nav=document.querySelector('#nav'),settings=document.querySelector('#settings');if(!nav||!settings)return;let b=nav.querySelector('[data-view="operatingManual"]'),s=document.querySelector('#operatingManual');if(!b){b=document.createElement('button');b.dataset.view='operatingManual';b.textContent='Manual';nav.insertBefore(b,nav.querySelector('[data-view="settings"]'))}if(!s){s=document.createElement('section');s.id='operatingManual';s.className='view';s.innerHTML='<div id="operatingManualRoot"></div>';settings.parentNode.insertBefore(s,settings)}b.onclick=()=>activate(s,b);['lifeos:signals','lifeos:insights','lifeos:recovery','lifeos:experiments'].forEach(e=>window.addEventListener(e,()=>{if(s.classList.contains('active'))render(s.querySelector('#operatingManualRoot'))}));if(document.documentElement.dataset.restoreView==='operatingManual'||localStorage.getItem('dreLifeOS_activeView')==='operatingManual')setTimeout(()=>activate(s,b),0)}
window.OperatingManual={model,render};document.readyState==='loading'?document.addEventListener('DOMContentLoaded',install,{once:true}):install();
})();