/* Dre After Dark · Life OS — Operating Manual v2 */
(()=>{'use strict';
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const sections=['Initiation Architecture','Recovery Architecture','Schedule Sensitivity','Cognitive & Creative Conditions','Domestic Environment','Reading & Intellectual Production','Leisure Ecology','Social & Relationship Patterns','Body & Care Context','Sleep / Wake Architecture','What Helps','Active Questions / Unresolved Evidence','What Apparently Does Not'];
const rank=m=>{m=String(m||'').toLowerCase();return /established|repeated|experiment evidence/.test(m)?3:/developing|emerging|early/.test(m)?2:/learning|investigation|insufficient|single/.test(m)?1:0};
const label=m=>rank(m)>=3?'ESTABLISHED':rank(m)===2?'EMERGING':rank(m)===1?'LEARNING':'UNDER INVESTIGATION';
function model(){
 let insight=window.InsightEngine?.model?.()||{insights:[]},recovery=window.RecoveryEngine?.summary?.()||{},experiments=window.ExperimentEngine?.all?.()||[],signals=window.LifeSignals?.query?.()||[],items=[];
 const add=x=>items.push({...x,level:rank(x.maturity)});
 (insight.insights||[]).forEach(x=>add({section:x.class==='schedule'?'Schedule Sensitivity':x.class==='body-environment'?'Body & Care Context':'Initiation Architecture',claim:x.text,maturity:x.confidence||'under investigation',evidence:x.evidence||{},source:'Insight Engine',why:x.why||''}));
 if(recovery.recovered){let raw=recovery.interventions||[],total=raw.reduce((n,x)=>n+x.n,0),weighted=total?raw.reduce((n,x)=>n+x.avgHours*x.n,0)/total:null,latency=weighted==null?'—':weighted<1?Math.round(weighted*60)+' minutes':(+weighted.toFixed(1))+' hours';add({section:'Recovery Architecture',claim:`Across ${recovery.recovered} measured recoveries, average recorded recovery latency is ${latency}.`,maturity:recovery.status,evidence:{episodes:recovery.episodes,recovered:recovery.recovered},source:'Recovery Intelligence'});raw.filter(x=>x.n>=2).forEach(x=>add({section:'What Helps',claim:`“${x.name}” has ${x.n} measured recoveries averaging ${x.avgHours<1?Math.round(x.avgHours*60)+' minutes':x.avgHours+' hours'}.`,maturity:x.evidence||recovery.status,evidence:{n:x.n,avgHours:x.avgHours},source:'Recovery Intelligence'}))}
 experiments.filter(x=>['completed','inconclusive'].includes(x.status)).forEach(x=>{let j=x.result?.systemConclusion?.judgment||'inconclusive',section=j==='weaken'?'What Apparently Does Not':j==='support'?'What Helps':'Active Questions / Unresolved Evidence',why=x.result?.systemConclusion?.why||x.result?.interpretation||x.status,conf=x.result?.systemConclusion?.confidence||'low';add({section,claim:`Experiment “${x.title}”: ${why}`,maturity:j==='inconclusive'?'under investigation':conf==='high'?'experiment evidence':'emerging',evidence:x.result||{},source:'Experiment Engine'})});
 let reading=signals.filter(x=>x.domain==='reading').length,publishing=signals.filter(x=>x.domain==='publishing').length;if(reading||publishing)add({section:'Reading & Intellectual Production',claim:`${reading} reading signals and ${publishing} publishing/performance signals are available for production-chain analysis.`,maturity:reading+publishing>=20?'developing':'under investigation',evidence:{reading,publishing},source:'Unified Signals'});
 let grouped=sections.map(name=>{let seen=new Set(),xs=items.filter(x=>x.section===name).sort((a,b)=>b.level-a.level).filter(x=>{let k=`${x.source}|${x.claim}`;if(seen.has(k))return false;seen.add(k);return true});return{name,items:xs}});
 return{generatedAt:new Date().toISOString(),signals:signals.length,sections:grouped,experiments:{running:experiments.filter(x=>x.status==='running').length,total:experiments.length},counts:{established:items.filter(x=>x.level===3).length,emerging:items.filter(x=>x.level===2).length,learning:items.filter(x=>x.level===1).length}};
}
function render(root){let m=model(),informed=m.sections.filter(x=>x.items.length),findings=m.sections.flatMap(s=>s.items.map(x=>({...x,section:s.name}))),est=findings.filter(x=>x.level===3),em=findings.filter(x=>x.level===2),learn=findings.filter(x=>x.level<=1),helps=m.sections.find(x=>x.name==='What Helps')?.items||[],questions=m.sections.find(x=>x.name==='Active Questions / Unresolved Evidence')?.items||[];root.innerHTML=`<section class="profile-cover card manual-command"><p class="eyebrow">OPERATING MANUAL · 3.0</p><h2>What Life OS knows about how you work.</h2><p class="profile-deck">Evidence first. Strong patterns stay visible; developing ideas remain clearly provisional.</p><div class="manual-metrics"><div><strong>${m.signals}</strong><small>signals</small></div><div><strong>${informed.length}/${m.sections.length}</strong><small>chapters informed</small></div><div><strong>${est.length}</strong><small>established</small></div><div><strong>${em.length}</strong><small>emerging</small></div></div>${est.length?`<div class="manual-now"><p class="eyebrow">ESTABLISHED NOW</p>${est.slice(0,3).map(x=>`<div class="manual-finding"><b>${esc(x.section)}</b><p>${esc(x.claim)}</p></div>`).join('')}</div>`:`<div class="manual-now"><p class="eyebrow">CURRENT EVIDENCE</p><p class="quiet">No finding has reached Established yet. Life OS will not promote a pattern simply to fill this space.</p></div>`}</section><details class="manual-section" ${helps.length?'open':''}><summary><span><b>What helps</b><small>${helps.length} evidence-backed finding${helps.length===1?'':'s'}</small></span></summary><div class="manual-body">${sectionHTML('What Helps',helps)}</div></details><details class="manual-section"><summary><span><b>Active questions</b><small>${questions.length||learn.length} things still being learned</small></span></summary><div class="manual-body">${sectionHTML('Active Questions / Unresolved Evidence',questions.length?questions:learn)}</div></details><details class="manual-section"><summary><span><b>Full operating manual</b><small>${m.sections.length} evidence chapters</small></span></summary><div class="manual-body manual-chapters">${m.sections.map(s=>`<article class="card"><p class="eyebrow">${esc(s.name.toUpperCase())}</p><h3>${s.items.length?s.items.length+' evidence-backed '+(s.items.length===1?'finding':'findings'):'Still learning'}</h3>${s.items.length?s.items.map((x,i)=>findingHTML(s.name,x,i)).join(''):'<p class="quiet">Life OS does not have enough evidence to write this chapter yet.</p>'}</article>`).join('')}</div></details><p class="manual-ladder quiet">Evidence ladder: Under investigation → Learning → Emerging → Established. Findings are revisable; empty chapters remain empty rather than becoming invented traits.</p>`;bindDetails(root)}
function findingHTML(name,x,i){return `<div class="care-note"><p class="eyebrow">${label(x.maturity)}</p><p>${esc(x.claim)}</p><div class="row"><small>${esc(x.source)} · revisable</small><button class="ghost" data-manual-detail="${esc(name)}|${i}">Why?</button></div></div>`}
function sectionHTML(name,items){return items.length?items.slice(0,8).map((x,i)=>findingHTML(name,x,i)).join(''):'<p class="quiet">Nothing has enough evidence for this section yet.</p>'}
function bindDetails(root){root.querySelectorAll('[data-manual-detail]').forEach(b=>b.onclick=()=>{let [name,i]=b.dataset.manualDetail.split('|'),x=model().sections.find(s=>s.name===name)?.items[+i];if(!x)return;let modal=document.querySelector('#modal'),c=document.querySelector('#modalContent');if(c)c.innerHTML=`<p class="eyebrow">EVIDENCE TRACE</p><h2>${esc(name)}</h2><p><b>${label(x.maturity)}</b></p><p>${esc(x.claim)}</p><h3>Why Life OS says this</h3><p>${esc(x.why||'This statement is generated from the source and evidence shown below.')}</p><p><b>Source:</b> ${esc(x.source)}</p><pre style="white-space:pre-wrap;font-size:.8rem">${esc(JSON.stringify(x.evidence||{},null,2))}</pre><p class="quiet">This is a revisable inference, not a permanent trait label.</p>`;modal?.classList.remove('hidden')})}
function activate(s,b){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));document.querySelectorAll('#nav button').forEach(x=>x.classList.remove('active'));s.classList.add('active');b.classList.add('active');try{localStorage.setItem('dreLifeOS_activeView','operatingManual')}catch{}render(s.querySelector('#operatingManualRoot'))}
function install(){let nav=document.querySelector('#nav'),settings=document.querySelector('#settings');if(!nav||!settings)return;let b=nav.querySelector('[data-view="operatingManual"]'),s=document.querySelector('#operatingManual');if(!b){b=document.createElement('button');b.dataset.view='operatingManual';b.textContent='Manual';nav.insertBefore(b,nav.querySelector('[data-view="settings"]'))}if(!s){s=document.createElement('section');s.id='operatingManual';s.className='view';s.innerHTML='<div id="operatingManualRoot"></div>';settings.parentNode.insertBefore(s,settings)}b.onclick=()=>activate(s,b);['lifeos:signals','lifeos:insights','lifeos:recovery','lifeos:experiments'].forEach(e=>window.addEventListener(e,()=>{if(s.classList.contains('active'))render(s.querySelector('#operatingManualRoot'))}));if(document.documentElement.dataset.restoreView==='operatingManual'||localStorage.getItem('dreLifeOS_activeView')==='operatingManual')setTimeout(()=>activate(s,b),0)}
window.OperatingManual={model,render};document.readyState==='loading'?document.addEventListener('DOMContentLoaded',install,{once:true}):install();
})();