/* Dre After Dark · Life OS — Pattern Engine · stabilized */
(()=>{const KEY='dreLifeOS',read=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return{}}},day=v=>String(v||'').slice(0,10),mean=a=>a.length?a.reduce((n,x)=>n+x,0)/a.length:null,fmt=n=>n==null?null:+n.toFixed(2);
const bodyKinds=s=>{let t=`${s.type||''} ${s.label||''} ${s.context?.area||''}`.toLowerCase();if(/sleep/.test(t))return'sleep';if(/hair|scalp/.test(t))return'hair';if(/skin|dermat/.test(t))return'skin';if(/nutrition|body|meal|food|weight|hydr/.test(t))return'nutrition-body';if(/medication|treatment/.test(t))return'treatment';if(/mental|psychi|therapy/.test(t))return'mental-health';return'physical-health'};
function signals(){return window.LifeSignals?.query?.()||read().signals||[]}
function profilesFrom(ss){let byDay=new Map();ss.forEach(x=>{let d=x.day||day(x.at);if(!d)return;if(!byDay.has(d))byDay.set(d,[]);byDay.get(d).push(x)});return[...byDay.entries()].sort((a,b)=>a[0].localeCompare(b[0])).map(([date,a])=>{let health=a.filter(x=>x.domain==='health'),house=a.filter(x=>x.domain==='house'),plant=a.filter(x=>x.domain==='plant'),behavior=a.filter(x=>!['health','house','plant','calendar'].includes(x.domain)),energy=a.map(x=>x.energy).filter(Boolean),counts={};health.forEach(x=>counts[bodyKinds(x)]=(counts[bodyKinds(x)]||0)+1);return{date,bodySignals:health.length,bodyKinds:counts,environmentSignals:house.length+plant.length,houseSignals:house.length,plantSignals:plant.length,behaviorSignals:behavior.length,habitSignals:a.filter(x=>x.domain==='habit').length,readingSignals:a.filter(x=>x.domain==='reading').length,publishingSignals:a.filter(x=>x.domain==='publishing').length,journalSignals:a.filter(x=>x.domain==='journal').length,relationshipSignals:a.filter(x=>x.domain==='relationship').length,energySamples:energy}})}
function profiles(){return profilesFrom(signals())}
function compareProfiles(p,field,min=3){let yes=p.filter(x=>x[field]>0),no=p.filter(x=>x[field]===0),keys=['habitSignals','readingSignals','publishingSignals','journalSignals','relationshipSignals','behaviorSignals'],metrics={};keys.forEach(k=>{let a=mean(yes.map(x=>x[k])),b=mean(no.map(x=>x[k]));metrics[k]={context:fmt(a),without:fmt(b),difference:a!=null&&b!=null?fmt(a-b):null}});return{status:yes.length>=min&&no.length>=min?'descriptive':'insufficient',sample:{contextDays:yes.length,comparisonDays:no.length},metrics}}
function bodyComparisons(){return compareProfiles(profiles(),'bodySignals')}function environmentComparisons(){return compareProfiles(profiles(),'environmentSignals')}
function careWindows(hours=48){let ss=signals(),care=ss.filter(x=>x.domain==='health'),behavior=ss.filter(x=>!['health','calendar'].includes(x.domain));return care.map(c=>{let ct=new Date(c.at).getTime(),near=behavior.filter(b=>Math.abs(new Date(b.at)-ct)<=hours*3600000);return{care:c,kind:bodyKinds(c),before:near.filter(b=>new Date(b.at)<ct),after:near.filter(b=>new Date(b.at)>=ct),nearby:near}})}
function environmentWindows(hours=24){let ss=signals(),env=ss.filter(x=>['house','plant'].includes(x.domain)),behavior=ss.filter(x=>!['house','plant','calendar'].includes(x.domain));return env.map(e=>{let t=new Date(e.at).getTime(),near=behavior.filter(b=>Math.abs(new Date(b.at)-t)<=hours*3600000);return{environment:e,nearby:near}})}
function hypothesesFrom(b,e){let out=[],names={habitSignals:'habit activity',readingSignals:'reading activity',publishingSignals:'publishing activity',journalSignals:'journal activity',relationshipSignals:'relationship reflection',behaviorSignals:'overall behavioral activity'};[[b,'body/health observation days'],[e,'environmental-maintenance days']].forEach(([c,label])=>{if(c.status!=='descriptive')return;Object.entries(c.metrics).forEach(([k,m])=>{if(m.difference!=null&&Math.abs(m.difference)>=.5)out.push({context:label,metric:k,text:`${names[k]} averaged ${m.context} signals on ${label} versus ${m.without} on comparison days (${m.difference>0?'+':''}${m.difference}).`,evidence:'descriptive association only'})})});if(!out.length)out.push({context:'body-environment',text:(b.status==='insufficient'||e.status==='insufficient')?'More repeated body/environment and comparison days are needed before Life OS presents longitudinal differences.':'No large descriptive body/environment differences are visible in the tracked behavioral categories yet.',evidence:'data readiness'});return out}
function hypotheses(){let p=profiles(),b=compareProfiles(p,'bodySignals'),e=compareProfiles(p,'environmentSignals');return hypothesesFrom(b,e)}
function model(){let ss=signals(),p=profilesFrom(ss),b=compareProfiles(p,'bodySignals'),e=compareProfiles(p,'environmentSignals'),cal=window.LifeSignals?.calendarComparisons?.()||null;return{generatedAt:new Date().toISOString(),signals:ss.length,classes:{schedule:cal,body:b,environment:e,cognition:{reading:ss.filter(x=>x.domain==='reading').length,publishing:ss.filter(x=>x.domain==='publishing').length}},hypotheses:hypothesesFrom(b,e),safety:'Observational associations are not diagnoses or causal findings.'}}
window.PatternEngine={profiles,bodyComparisons,environmentComparisons,careWindows,environmentWindows,hypotheses,model};

})();