/* Dre After Dark · Life OS — Settings Command 2.0 */
(()=>{'use strict';const $=s=>document.querySelector(s);
function style(){if($('#settingsCommandStyle'))return;let x=document.createElement('style');x.id='settingsCommandStyle';x.textContent=`#settings.settings-v2{max-width:980px;margin:0 auto}.settings-v2 .settings-intro{margin:0 0 1.2rem}.settings-v2 .settings-intro h1{margin:.3rem 0 .5rem}.settings-v2 .settings-command{background:linear-gradient(145deg,rgba(86,17,43,.82),rgba(31,16,23,.92));border:1px solid rgba(198,153,95,.24);border-radius:24px;padding:1.25rem;margin-bottom:1rem}.settings-command-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:.65rem;margin-top:1rem}.settings-stat{background:rgba(8,7,9,.72);border:1px solid rgba(255,255,255,.06);border-radius:16px;padding:.85rem}.settings-stat b{display:block;color:var(--gold,#caa86b);font-size:1.35rem}.settings-stat small{opacity:.72}.settings-v2 details.settings-group{border:1px solid rgba(255,255,255,.08);border-radius:20px;margin:.8rem 0;background:rgba(18,12,16,.7);overflow:hidden}.settings-group>summary{list-style:none;cursor:pointer;padding:1rem 1.1rem;display:flex;align-items:center;justify-content:space-between;gap:1rem}.settings-group>summary::-webkit-details-marker{display:none}.sg-title{font-weight:700}.sg-sub{display:block;opacity:.65;font-size:.82rem;margin-top:.2rem;font-weight:400}.sg-plus{font-size:1.55rem;color:var(--gold,#caa86b)}details[open] .sg-plus{transform:rotate(45deg)}.sg-body{padding:0 .75rem .75rem}.sg-body>.card,.sg-body>.grid,.sg-body>div>.card{margin:.65rem 0}.sg-body .grid.two{display:grid;grid-template-columns:1fr;gap:.65rem}@media(max-width:560px){.settings-stat{padding:.7rem}.settings-stat b{font-size:1.15rem}}`;document.head.appendChild(x)}
function group(id,t,sub){let d=$('#'+id);if(d)return d;d=document.createElement('details');d.id=id;d.className='settings-group';d.innerHTML=`<summary><span><span class="sg-title">${t}</span><span class="sg-sub">${sub}</span></span><span class="sg-plus">+</span></summary><div class="sg-body"></div>`;return d}
function move(g,n){if(n&&n.parentElement!==g.querySelector('.sg-body'))g.querySelector('.sg-body').appendChild(n)}
async function status(){let d={};try{d=window.LifeStore?.read?.()||JSON.parse(localStorage.getItem('dreLifeOS')||'{}')}catch{};let session=null;try{session=await window.LifeAuth?.getSession?.()}catch{};let h=$('#settingsCommandStats');if(h)h.innerHTML=`<div class="settings-stat"><b>${d.personalLabs?.scans?.length||0}</b><small>saved scans</small></div><div class="settings-stat"><b>${session?'✓':'—'}</b><small>cloud identity</small></div><div class="settings-stat"><b>${d.calendar?.events?.length||0}</b><small>calendar events</small></div>`}
function arrange(){let s=$('#settings');if(!s)return;style();s.classList.add('settings-v2');if(!$('#settingsIntro')){let h=document.createElement('div');h.id='settingsIntro';h.className='settings-intro';h.innerHTML='<p class="eyebrow">LIFE OS · SYSTEM CONTROL</p><h1>Settings</h1><p>Connect, protect and maintain the system. Open a section only when you need it.</p>';s.prepend(h)}if(!$('#settingsCommand')){let h=document.createElement('article');h.id='settingsCommand';h.className='settings-command';h.innerHTML='<p class="eyebrow">SYSTEM COMMAND · 2.0</p><h2>Everything in its place.</h2><p class="quiet">Daily use stays out of Settings. This desk is for capture, connections, data and system health.</p><div id="settingsCommandStats" class="settings-command-grid"></div>';$('#settingsIntro').after(h)}
let defs=[['settingsCapture','📷 Capture + Personal Labs','Scanner, picture desk and structured personal records'],['settingsConnections','☁️ Connections','Life OS Cloud and Google Calendar'],['settingsData','🗄️ Backup + data','Export, import and local data controls'],['settingsAtmosphere','✒️ Atmosphere','Quote library and personal expression'],['settingsHealth','🛡️ System health','Privacy footprint and release readiness']],a=$('#settingsCommand');for(let z of defs){let g=group(...z);if(!g.parentElement)a.insertAdjacentElement('afterend',g);a=g}
move($('#settingsCapture'),$('#smartScanner'));move($('#settingsCapture'),$('#scanLibrary'));move($('#settingsCapture'),$('#personalLabs'));
let grid=$('#settings > .grid.two');if(grid){let cards=[...grid.children],vault=cards.find(x=>/THE VAULT/i.test(x.textContent)),cloud=cards.find(x=>/CLOUD IDENTITY/i.test(x.textContent));move($('#settingsData'),vault);move($('#settingsConnections'),cloud);move($('#settingsConnections'),$('#googleCalendarCard'));if(!grid.children.length)grid.remove()}
let quote=[...s.children].find(x=>x.matches?.('article.card')&&/Quote library/i.test(x.textContent));move($('#settingsAtmosphere'),quote);move($('#settingsHealth'),$('#privacyControls'));move($('#settingsHealth'),$('#releaseReadiness'));status()}
function activate(){setTimeout(()=>{arrange();window.LifePrivacy?.render?.();window.LifeRelease?.render?.();setTimeout(arrange,120)},100)}
function boot(){let b=document.querySelector('#nav button[data-view="settings"]');if(b&&!b.dataset.settingsCommand){b.dataset.settingsCommand='1';b.addEventListener('click',activate)}if($('#settings')?.classList.contains('active'))activate()}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',boot,{once:true}):boot();window.SettingsCommand={render:activate};})();