import fs from "node:fs"; import crypto from "node:crypto"; import {Decoder,Stream} from "@garmin/fitsdk";
const file=process.argv[2]; if(!file) throw new Error("Usage: node decode-fit.mjs activity.fit");
const buf=fs.readFileSync(file),stream=Stream.fromBuffer(buf); if(!Decoder.isFIT(stream)) throw new Error("Not a FIT file");
const decoder=new Decoder(stream); if(!decoder.checkIntegrity()) throw new Error("FIT integrity/CRC check failed");
const {messages,errors}=decoder.read({mergeHeartRates:true,convertDateTimesToDates:true});
const sessions=messages.sessionMesgs||messages.session||[],records=messages.recordMesgs||messages.record||[],s=sessions[0]||{};
const iso=v=>v instanceof Date?v.toISOString():(v??null);
const startedAt=iso(s.startTime||records[0]?.timestamp),endedAt=iso(s.timestamp||records.at(-1)?.timestamp);
const sourceId=crypto.createHash("sha256").update(buf).digest("hex").slice(0,32);
const out={source:"fit",sourceId,startedAt,endedAt,sport:s.sport||null,subSport:s.subSport||null,durationSeconds:s.totalTimerTime??s.totalElapsedTime??null,distanceM:s.totalDistance??null,calories:s.totalCalories??null,avgHr:s.avgHeartRate??null,maxHr:s.maxHeartRate??null,avgSpeed:s.avgSpeed??null,records:records.length,decoderErrors:errors||[]};
console.log(JSON.stringify(out,null,2));
